import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
const migration=fs.readFileSync(new URL('../../../supabase/migrations/0030_m13_fiscal_a1.sql',import.meta.url),'utf8');
const preflight=fs.readFileSync(new URL('../../../supabase/preflight/0030_m13_fiscal_a1_preflight.sql',import.meta.url),'utf8');
const rollback=fs.readFileSync(new URL('../../../supabase/rollback/0030_m13_fiscal_a1.rollback.sql',import.meta.url),'utf8');
const pgtap=fs.readFileSync(new URL('../../../supabase/tests/0030_m13_fiscal_a1.test.sql',import.meta.url),'utf8');
test('migration é transacional',()=>{assert.match(migration,/^begin;/m);assert.match(migration,/commit;\s*$/)});
test('migration cria 14 tabelas fiscais',()=>assert.equal((migration.match(/create table public\./g)||[]).length,14));
test('todas as tabelas entram no bloco RLS',()=>assert.match(migration,/foreach t in array array\[[^\]]*erp_fiscal_webhook_inbox/));
test('PFX e CSC não são colunas',()=>{assert.doesNotMatch(migration,/\b(pfx|p12|certificate_password|csc_value)\s+(text|bytea)/i)});
test('preflight bloqueia objetos preexistentes',()=>assert.match(preflight,/Objetos M13 já existem/));
test('preflight tem marcador determinístico',()=>assert.match(preflight,/M13_0030_PREFLIGHT_OK/));
test('rollback remove funções antes das tabelas',()=>assert.ok(rollback.indexOf('drop function')<rollback.indexOf('drop table')));
test('pgTAP declara 100 asserções',()=>assert.match(pgtap,/select plan\(100\)/));
test('pgTAP termina em rollback',()=>assert.match(pgtap,/rollback;\s*$/));
test('IDs externos opcionais usam índices parciais',()=>{assert.doesNotMatch(migration,/unique nulls not distinct\(tenant_id,provider,provider_document_id\)/);assert.match(migration,/provider_document_unique[^;]+where provider_document_id is not null/)});
test('documento preserva estabelecimento e série',()=>assert.match(migration,/foreign key\(tenant_id,series_id,establishment_id,environment,model,series\)/));
test('documento referencia schema por modelo e versão',()=>assert.match(migration,/foreign key\(model,schema_version\)references public\.erp_fiscal_schema_versions/));
test('contingência possui vínculo obrigatório com modelo 65',()=>assert.match(migration,/document_model text not null default '65'check\(document_model='65'\)/));
test('referência criptográfica aceita apenas identificador de cofre',()=>assert.match(migration,/secret_ref~'\^\(vault\|hsm\|provider\|seal\):\/\//));
test('produção possui kill switch também no SQL',()=>assert.ok((migration.match(/fiscal production disabled/g)||[]).length>=2));
test('evento divergente do estado é recusado',()=>assert.match(migration,/event and status mismatch/));
test('operador não pode declarar autorização fiscal',()=>assert.match(migration,/operator transition forbidden/));
test('broker não pode cancelar documento',()=>assert.match(migration,/broker transition forbidden/));
