import test from'node:test';import assert from'node:assert/strict';import{createHash}from'node:crypto';import{buildEnviNFe,calculateAccessKeyDigit,composeSyntheticAccessKey,deterministicBatchId,LocalBatchRegistry,reconcileNFeTotals,validateAccessKey}from'../src/nfe-business.mjs';
const key=()=>composeSyntheticAccessKey({stateCode:'35',yearMonth:'2608',series:'001',number:'000000001',numericCode:'00000001'});
const totals=()=>({items:[{productCents:100,discountCents:0}],totals:{freightCents:0,insuranceCents:0,otherCents:0,ipiCents:0,stCents:0,desonerationCents:0,invoiceCents:100},payments:[{method:'90',amountCents:0}]});
test('chave sintética possui 44 dígitos',()=>assert.match(key(),/^\d{44}$/));
test('dígito da chave é validado',()=>assert.equal(validateAccessKey(key()),true));
test('alteração na chave é rejeitada',()=>assert.throws(()=>validateAccessKey(`${key().slice(0,43)}${(Number(key()[43])+1)%10}`),/REJECTION_236/));
test('base da chave exige 43 dígitos',()=>assert.throws(()=>calculateAccessKeyDigit('123'),/REJECTION_236/));
test('CNPJ não sintético é recusado',()=>assert.throws(()=>composeSyntheticAccessKey({stateCode:'35',yearMonth:'2608',syntheticTaxId:'1'.repeat(14),model:'55',series:'001',number:'000000001',emissionType:'1',numericCode:'00000001'}),/SYNTHETIC_SCOPE/));
test('modelo diferente de 55 é recusado',()=>assert.throws(()=>composeSyntheticAccessKey({stateCode:'35',yearMonth:'2608',model:'65',series:'001',number:'000000001',numericCode:'00000001'}),/SYNTHETIC_SCOPE/));
test('totais em centavos reconciliam',()=>assert.equal(reconcileNFeTotals(totals()).invoiceCents,100));
test('modo sem pagamento é explícito',()=>assert.equal(reconcileNFeTotals(totals()).paymentMode,'no_payment'));
test('total divergente é rejeitado',()=>{const value=totals();value.totals.invoiceCents=99;assert.throws(()=>reconcileNFeTotals(value),/REJECTION_564/)});
test('pagamento divergente é rejeitado',()=>{const value=totals();value.payments=[{method:'01',amountCents:99}];assert.throws(()=>reconcileNFeTotals(value),/REJECTION_865/)});
test('desconto participa da reconciliação',()=>{const value=totals();value.items[0].discountCents=10;value.totals.invoiceCents=90;assert.equal(reconcileNFeTotals(value).invoiceCents,90)});
test('lote é determinístico',()=>{const input={accessKey:key(),idempotencyKey:'synthetic-idempotency-001'};assert.equal(deterministicBatchId(input),deterministicBatchId(input))});
test('lotes mudam com idempotência',()=>assert.notEqual(deterministicBatchId({accessKey:key(),idempotencyKey:'synthetic-idempotency-001'}),deterministicBatchId({accessKey:key(),idempotencyKey:'synthetic-idempotency-002'})));
test('lote possui até 15 dígitos',()=>assert.match(deterministicBatchId({accessKey:key(),idempotencyKey:'synthetic-idempotency-001'}),/^\d{1,15}$/));
test('envelope local usa versão 4.00',()=>assert.match(buildEnviNFe({batchId:'1',accessKey:key(),nfeXml:'<NFe xmlns="http://www.portalfiscal.inf.br/nfe"><synthetic/></NFe>'}),/<enviNFe[^>]+versao="4.00"/));
test('envelope recusa XML assinado',()=>assert.throws(()=>buildEnviNFe({batchId:'1',accessKey:key(),nfeXml:'<NFe><Signature/></NFe>'}),/REJECTION_UNSAFE_XML/));
test('envelope recusa identidade da piloto',()=>assert.throws(()=>buildEnviNFe({batchId:'1',accessKey:key(),nfeXml:`<NFe><CNPJ>${'09'+'050756'+'000110'}</CNPJ></NFe>`}),/REJECTION_UNSAFE_XML/));
test('registro idempotente não duplica lote',()=>{const registry=new LocalBatchRegistry();assert.equal(registry.submit({batchId:'1',contentHash:'a'.repeat(64)}).status,'accepted_local');assert.equal(registry.submit({batchId:'1',contentHash:'a'.repeat(64)}).status,'duplicate');assert.equal(registry.size(),1)});
test('conflito do mesmo lote é rejeitado',()=>{const registry=new LocalBatchRegistry();registry.submit({batchId:'1',contentHash:'a'.repeat(64)});assert.throws(()=>registry.submit({batchId:'1',contentHash:'b'.repeat(64)}),/REJECTION_539/)});
test('simulação não usa rede ou persistência',()=>{const source=[calculateAccessKeyDigit,buildEnviNFe,LocalBatchRegistry].map(String).join();assert.doesNotMatch(source,/fetch|writeFile|database|Invoke-WebRequest/i)});
