import test from'node:test';import assert from'node:assert/strict';import{LocalNFeAuthorizationSimulator,reconcileAuthorization,transitionAuthorization}from'../src/nfe-authorization.mjs';
const input=(scenario='authorized')=>({accessKey:'1'.repeat(44),batchId:'1',contentHash:'a'.repeat(64),scenario});
test('fluxo nominal permite estados esperados',()=>{assert.equal(transitionAuthorization('draft','submitted'),'submitted');assert.equal(transitionAuthorization('submitted','received'),'received');assert.equal(transitionAuthorization('received','processing'),'processing');assert.equal(transitionAuthorization('processing','authorized'),'authorized')});
test('estado terminal não retrocede',()=>assert.throws(()=>transitionAuthorization('authorized','processing'),/INVALID_AUTHORIZATION_TRANSITION/));
test('timeout exige consulta',()=>assert.equal(transitionAuthorization('timeout','querying'),'querying'));
test('autorização sintética retorna protocolo',()=>assert.match(new LocalNFeAuthorizationSimulator().submit(input()).protocol,/^SYNTH-PROTOCOL-/));
test('rejeição sintética é determinística',()=>assert.equal(new LocalNFeAuthorizationSimulator().submit(input('rejected')).code,'SYNTHETIC_REJECTION'));
test('timeout retorna recibo e consulta',()=>{const out=new LocalNFeAuthorizationSimulator().submit(input('timeout'));assert.equal(out.action,'query_status');assert.match(out.receipt,/^SYNTH-/)});
test('consulta posterior autoriza sem nova emissão',()=>{const sim=new LocalNFeAuthorizationSimulator(),first=sim.submit(input('timeout')),out=sim.query(first.receipt);assert.equal(out.status,'authorized');assert.equal(sim.size(),1)});
test('consulta pode permanecer processando',()=>{const sim=new LocalNFeAuthorizationSimulator(),first=sim.submit(input('timeout'));assert.equal(sim.query(first.receipt,{resolveAs:'pending'}).action,'query_later')});
test('consulta pode resolver rejeição',()=>{const sim=new LocalNFeAuthorizationSimulator(),first=sim.submit(input('timeout'));assert.equal(sim.query(first.receipt,{resolveAs:'rejected'}).status,'rejected')});
test('recibo desconhecido retorna not found',()=>assert.equal(new LocalNFeAuthorizationSimulator().query('missing').status,'not_found'));
test('reenvio idêntico não duplica documento',()=>{const sim=new LocalNFeAuthorizationSimulator();sim.submit(input());assert.equal(sim.submit(input()).status,'duplicate');assert.equal(sim.size(),1)});
test('duplicidade autorizada devolve protocolo',()=>{const sim=new LocalNFeAuthorizationSimulator();const first=sim.submit(input());const second=sim.submit(input());assert.equal(second.protocol,first.protocol)});
test('mesma chave com conteúdo diferente é recusada',()=>{const sim=new LocalNFeAuthorizationSimulator();sim.submit(input());assert.throws(()=>sim.submit({...input(),contentHash:'b'.repeat(64)}),/REJECTION_539/)});
test('protocolo remoto é importado',()=>assert.equal(reconcileAuthorization({localState:'timeout',remoteState:'authorized',remoteProtocol:'p'}),'import_protocol'));
test('protocolo igual não altera estado',()=>assert.equal(reconcileAuthorization({localState:'authorized',remoteState:'authorized',localProtocol:'p',remoteProtocol:'p'}),'no_op'));
test('protocolos divergentes exigem revisão',()=>assert.equal(reconcileAuthorization({localState:'authorized',remoteState:'authorized',localProtocol:'a',remoteProtocol:'b'}),'manual_protocol_conflict'));
test('rejeição remota é importada',()=>assert.equal(reconcileAuthorization({localState:'processing',remoteState:'rejected'}),'import_rejection'));
test('timeout com ausência agenda nova consulta',()=>assert.equal(reconcileAuthorization({localState:'timeout',remoteState:'not_found'}),'wait_and_query'));
test('entradas inválidas são recusadas',()=>assert.throws(()=>new LocalNFeAuthorizationSimulator().submit({...input(),accessKey:'1'}),/INVALID_SIMULATION_INPUT/));
test('simulador não contém acesso de rede ou disco',()=>assert.doesNotMatch(LocalNFeAuthorizationSimulator.toString(),/fetch|HttpClient|writeFile|database|supabase/i));
