import test from 'node:test';import assert from 'node:assert/strict';import {TAX_PROFILES,validateTenantTaxProfile,resolveTenantTaxProfile} from '../src/tax-profiles.mjs';
const normal=()=>({tenantId:'tenant-synthetic-a',profileCode:'NORMAL_RPA',declaredCrt:'3',taxCodeKind:'CST',taxCode:'00',ncm:'61091000',cfop:'5102',environment:'homologation',ruleSetVersion:'NFE_4.00_2026.06',accountantApproved:true});
test('RPA sintetico usa CRT 3 e CST',()=>assert.equal(validateTenantTaxProfile(normal()).ready,true));
test('RPA com CSOSN bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),taxCodeKind:'CSOSN',taxCode:'102'}).blockers.includes('taxCodeKindMismatch')));
test('RPA com CRT simples bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),declaredCrt:'1'}).blockers.includes('crtMismatch')));
test('Simples sintetico usa CRT 1 e CSOSN',()=>assert.equal(validateTenantTaxProfile({...normal(),profileCode:'SIMPLE_NATIONAL',declaredCrt:'1',taxCodeKind:'CSOSN',taxCode:'102'}).ready,true));
test('excesso de sublimite usa CRT 2 e CST',()=>assert.equal(validateTenantTaxProfile({...normal(),profileCode:'SIMPLE_EXCESS',declaredCrt:'2'}).ready,true));
test('MEI existe mas permanece bloqueado',()=>assert.ok(validateTenantTaxProfile({...normal(),profileCode:'MEI',declaredCrt:'4',taxCodeKind:'CSOSN',taxCode:'102'}).blockers.includes('profileNotReleased')));
test('perfil desconhecido bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),profileCode:'OTHER'}).blockers.includes('profileUnknown')));
test('CST invalido bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),taxCode:'99'}).blockers.includes('cstUnsupported')));
test('NCM invalido bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),ncm:'123'}).blockers.includes('ncmInvalid')));
test('CFOP de entrada bloqueia emissao de venda',()=>assert.ok(validateTenantTaxProfile({...normal(),cfop:'1102'}).blockers.includes('cfopInvalid')));
test('producao bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),environment:'production'}).blockers.includes('productionForbidden')));
test('regra nao versionada bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),ruleSetVersion:'latest'}).blockers.includes('ruleSetUnpinned')));
test('aprovacao contabil e obrigatoria',()=>assert.ok(validateTenantTaxProfile({...normal(),accountantApproved:false}).blockers.includes('accountantApprovalRequired')));
test('tenant ausente bloqueia',()=>assert.ok(validateTenantTaxProfile({...normal(),tenantId:''}).blockers.includes('tenantRequired')));
test('resolver nao cruza tenants',()=>{const bindings=[{tenantId:'tenant-a',profileCode:'NORMAL_RPA'},{tenantId:'tenant-b',profileCode:'SIMPLE_NATIONAL'}];assert.equal(resolveTenantTaxProfile(bindings,'tenant-a').profileCode,'NORMAL_RPA');assert.throws(()=>resolveTenantTaxProfile(bindings,'tenant-c'),/NOT_FOUND/)});
test('validacao nunca gera ou transmite XML',()=>{const result=validateTenantTaxProfile(normal());assert.equal(result.xmlGenerated||result.signed||result.persisted||result.transmitted||result.productionAccessed,false)});
test('catalogo declara quatro perfis sinteticos',()=>assert.deepEqual(Object.keys(TAX_PROFILES),['NORMAL_RPA','SIMPLE_NATIONAL','SIMPLE_EXCESS','MEI']));
