begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions,pgtap;
select plan(52);
select ok(to_regclass(format('public.%I',table_name)) is not null,format('tabela %s existe',table_name)) from unnest(array['erp_quotes','erp_quote_items','erp_sales_orders','erp_sales_order_items','erp_payment_methods','erp_cash_registers','erp_cash_sessions','erp_sales','erp_sale_items','erp_sale_payments','erp_cash_movements','erp_returns','erp_return_items','erp_sale_receipts']) names(table_name);
select ok(c.relrowsecurity,format('RLS ativo em %s',c.relname)) from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relname=any(array['erp_quotes','erp_quote_items','erp_sales_orders','erp_sales_order_items','erp_payment_methods','erp_cash_registers','erp_cash_sessions','erp_sales','erp_sale_items','erp_sale_payments','erp_cash_movements','erp_returns','erp_return_items','erp_sale_receipts']) order by c.relname;
select ok(not has_table_privilege('anon',format('public.%I',table_name),'SELECT'),format('anon não lê %s',table_name)) from unnest(array['erp_quotes','erp_sales','erp_sale_payments','erp_cash_movements']) names(table_name);
select ok(has_table_privilege('authenticated',format('public.%I',table_name),'SELECT'),format('authenticated lê %s sob RLS',table_name)) from unnest(array['erp_quotes','erp_sales','erp_sale_payments','erp_cash_movements']) names(table_name);
select ok(not has_table_privilege('authenticated',format('public.%I',table_name),'DELETE'),format('authenticated não exclui %s',table_name)) from unnest(array['erp_quotes','erp_sales','erp_sale_payments','erp_cash_movements']) names(table_name);
select ok(not has_table_privilege('authenticated',format('public.%I',table_name),'UPDATE'),format('documento imutável %s',table_name)) from unnest(array['erp_sales','erp_sale_payments','erp_cash_movements','erp_sale_receipts']) names(table_name);
select is((select count(*)::integer from public.erp_permissions where key in('sales.read','sales.quote','sales.order','sales.complete','sales.return','sales.discount','payments.read','payments.manage','payments.refund','cash.read','cash.operate','cash.close','cash.adjust')),13,'treze permissões M07 existem');
select ok(not has_function_privilege('anon','public.erp_open_cash_session(uuid,uuid,numeric,text)','EXECUTE'),'anon não abre caixa');
select ok(has_function_privilege('authenticated','public.erp_open_cash_session(uuid,uuid,numeric,text)','EXECUTE'),'authenticated abre caixa por RPC protegida');
select ok(not has_function_privilege('anon','public.erp_complete_sale(uuid,uuid,text)','EXECUTE'),'anon não conclui venda');
select ok(has_function_privilege('authenticated','public.erp_complete_sale(uuid,uuid,text)','EXECUTE'),'authenticated conclui venda por RPC protegida');
select ok(exists(select 1 from pg_constraint where conname='erp_sales_tenant_id_idempotency_key_key'),'venda idempotente por tenant');
select ok(exists(select 1 from pg_constraint where conname='erp_sale_payments_tenant_id_idempotency_key_key'),'pagamento idempotente por tenant');
select ok(exists(select 1 from pg_constraint where conname='erp_cash_movements_tenant_id_idempotency_key_key'),'caixa idempotente por tenant');
select * from finish();
rollback;
