begin;set local role postgres;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions,pgtap;select plan(68);
select ok(to_regclass(format('public.%I',table_name))is not null,format('tabela %s existe',table_name))from unnest(array['erp_assets','erp_asset_identifiers','erp_asset_meter_readings','erp_vehicles','erp_appointments','erp_appointment_resources','erp_service_orders','erp_service_order_items','erp_service_order_events','erp_service_assignments','erp_work_logs','erp_inspections','erp_inspection_items','erp_service_attachments','erp_service_approvals','erp_service_warranties','erp_warranty_events'])names(table_name);
select ok(c.relrowsecurity,format('RLS ativo em %s',c.relname))from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'and c.relname=any(array['erp_assets','erp_asset_identifiers','erp_asset_meter_readings','erp_vehicles','erp_appointments','erp_appointment_resources','erp_service_orders','erp_service_order_items','erp_service_order_events','erp_service_assignments','erp_work_logs','erp_inspections','erp_inspection_items','erp_service_attachments','erp_service_approvals','erp_service_warranties','erp_warranty_events'])order by c.relname;
select ok(not has_table_privilege('anon',format('public.%I',table_name),'SELECT'),format('anon não lê %s',table_name))from unnest(array['erp_assets','erp_appointments','erp_service_orders','erp_service_attachments','erp_service_approvals'])names(table_name);
select ok(has_table_privilege('authenticated',format('public.%I',table_name),'SELECT'),format('authenticated lê %s sob RLS',table_name))from unnest(array['erp_assets','erp_appointments','erp_service_orders','erp_service_order_items','erp_service_warranties'])names(table_name);
select ok(not has_table_privilege('authenticated',format('public.%I',table_name),'DELETE'),format('authenticated não exclui %s',table_name))from unnest(array['erp_assets','erp_appointments','erp_service_orders','erp_service_order_events','erp_service_warranties'])names(table_name);
select is((select count(*)::integer from public.erp_permissions where key in('services.read','services.manage','services.diagnose','services.approve','services.execute','services.complete','services.warranty')),7,'sete permissões M09 existem');
select ok(not has_function_privilege('anon','public.erp_schedule_appointment(uuid,uuid,uuid,uuid,text,timestamptz,timestamptz,text,text,text)','EXECUTE'),'anon não agenda');
select ok(has_function_privilege('authenticated','public.erp_schedule_appointment(uuid,uuid,uuid,uuid,text,timestamptz,timestamptz,text,text,text)','EXECUTE'),'authenticated agenda por RPC');
select ok(not has_function_privilege('anon','public.erp_complete_service_order(uuid,uuid,text)','EXECUTE'),'anon não conclui OS');
select ok(has_function_privilege('authenticated','public.erp_complete_service_order(uuid,uuid,text)','EXECUTE'),'authenticated conclui OS por RPC');
select ok(exists(select 1 from pg_constraint where conname='erp_assets_tenant_id_code_key'),'ativo único por tenant');
select ok(exists(select 1 from pg_constraint where conname='erp_asset_identifiers_tenant_id_kind_value_normalized_key'),'identificador único por tenant');
select ok(exists(select 1 from pg_constraint where conname='erp_appointments_tenant_id_idempotency_key_key'),'agenda idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_service_orders_tenant_id_idempotency_key_key'),'OS idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_service_orders_tenant_id_sale_id_key'),'venda única por OS');
select ok(exists(select 1 from pg_constraint where conname='erp_service_order_events_tenant_id_idempotency_key_key'),'evento idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_work_logs_tenant_id_idempotency_key_key'),'tempo idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_service_approvals_tenant_id_idempotency_key_key'),'aprovação idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_service_warranties_tenant_id_service_order_id_key'),'garantia única por OS');
select ok(exists(select 1 from pg_constraint where conname='erp_warranty_events_tenant_id_idempotency_key_key'),'garantia rastreável');
select ok((select prosecdef from pg_proc where oid='public.erp_schedule_appointment(uuid,uuid,uuid,uuid,text,timestamptz,timestamptz,text,text,text)'::regprocedure),'agenda security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_complete_service_order(uuid,uuid,text)'::regprocedure),'conclusão security definer');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_service_attachments'::regclass and contype='c'),'anexo possui validação de caminho');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_service_orders'::regclass and contype='c'),'OS possui máquina de estados');
select * from finish();rollback;
