begin;set local role postgres;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions,pgtap;select plan(72);
select ok(to_regclass(format('public.%I',table_name))is not null,format('tabela %s existe',table_name))from unnest(array['erp_dining_areas','erp_dining_tables','erp_table_sessions','erp_table_session_events','erp_food_tabs','erp_food_tab_guests','erp_food_tab_events','erp_food_orders','erp_food_order_items','erp_modifier_groups','erp_modifiers','erp_food_order_item_modifiers','erp_recipe_yields','erp_kitchen_stations','erp_kitchen_tickets','erp_kitchen_ticket_items','erp_food_fulfillments','erp_food_tab_splits'])names(table_name);
select ok(c.relrowsecurity,format('RLS ativo em %s',c.relname))from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'and c.relname=any(array['erp_dining_areas','erp_dining_tables','erp_table_sessions','erp_table_session_events','erp_food_tabs','erp_food_tab_guests','erp_food_tab_events','erp_food_orders','erp_food_order_items','erp_modifier_groups','erp_modifiers','erp_food_order_item_modifiers','erp_recipe_yields','erp_kitchen_stations','erp_kitchen_tickets','erp_kitchen_ticket_items','erp_food_fulfillments','erp_food_tab_splits'])order by c.relname;
select ok(not has_table_privilege('anon',format('public.%I',table_name),'SELECT'),format('anon não lê %s',table_name))from unnest(array['erp_dining_tables','erp_food_tabs','erp_food_orders','erp_kitchen_tickets','erp_food_tab_splits'])names(table_name);
select ok(has_table_privilege('authenticated',format('public.%I',table_name),'SELECT'),format('authenticated lê %s sob RLS',table_name))from unnest(array['erp_dining_tables','erp_food_tabs','erp_food_order_items','erp_kitchen_tickets','erp_food_fulfillments'])names(table_name);
select ok(not has_table_privilege('authenticated',format('public.%I',table_name),'DELETE'),format('authenticated não exclui %s',table_name))from unnest(array['erp_table_sessions','erp_food_tabs','erp_food_tab_events','erp_kitchen_tickets','erp_food_tab_splits'])names(table_name);
select is((select count(*)::integer from public.erp_permissions where key in('food.read','food.manage','food.order','food.kitchen','food.cancel','food.discount','food.close')),7,'sete permissões M10 existem');
select ok(not has_function_privilege('anon','public.erp_open_table_session(uuid,uuid,integer,text)','EXECUTE'),'anon não abre mesa');select ok(has_function_privilege('authenticated','public.erp_open_table_session(uuid,uuid,integer,text)','EXECUTE'),'authenticated abre mesa por RPC');
select ok(not has_function_privilege('anon','public.erp_close_food_tab(uuid,uuid,integer,text)','EXECUTE'),'anon não fecha comanda');select ok(has_function_privilege('authenticated','public.erp_close_food_tab(uuid,uuid,integer,text)','EXECUTE'),'authenticated fecha comanda por RPC');
select ok(exists(select 1 from pg_indexes where indexname='erp_table_sessions_one_open'),'uma sessão aberta por mesa');
select ok(exists(select 1 from pg_constraint where conname='erp_table_sessions_tenant_id_idempotency_key_key'),'sessão idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_food_tabs_tenant_id_idempotency_key_key'),'comanda idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_food_tabs_tenant_id_sale_id_key'),'venda única por comanda');
select ok(exists(select 1 from pg_constraint where conname='erp_food_tab_events_tenant_id_idempotency_key_key'),'evento de comanda idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_food_orders_tenant_id_idempotency_key_key'),'pedido idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_food_order_items_tenant_id_idempotency_key_key'),'item idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_kitchen_tickets_tenant_id_idempotency_key_key'),'ticket idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_food_fulfillments_tenant_id_idempotency_key_key'),'entrega idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_food_tab_splits_tenant_id_idempotency_key_key'),'rateio idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_recipe_yields_tenant_id_composition_id_version_key'),'receita versionada');
select ok(exists(select 1 from pg_constraint where conname='erp_modifier_groups_check'),'limites de adicionais coerentes');
select ok((select prosecdef from pg_proc where oid='public.erp_open_table_session(uuid,uuid,integer,text)'::regprocedure),'abertura security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_close_food_tab(uuid,uuid,integer,text)'::regprocedure),'fechamento security definer');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_food_tabs'::regclass and contype='c'),'comanda possui máquina de estados');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_kitchen_tickets'::regclass and contype='c'),'cozinha possui máquina de estados');
select * from finish();rollback;
