begin;set local role postgres;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions,pgtap;select plan(87);
select ok(to_regclass(format('public.%I',table_name))is not null,format('tabela %s existe',table_name))from unnest(array['erp_support_queues','erp_support_queue_members','erp_sla_policies','erp_sla_targets','erp_support_tickets','erp_support_ticket_events','erp_support_messages','erp_support_attachments','erp_ticket_assignments','erp_ticket_sla_clocks','erp_managed_devices','erp_device_identifiers','erp_remote_consents','erp_remote_access_grants','erp_remote_sessions','erp_remote_session_events','erp_remote_session_artifacts'])names(table_name);
select ok(c.relrowsecurity,format('RLS ativo em %s',c.relname))from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'and c.relname=any(array['erp_support_queues','erp_support_queue_members','erp_sla_policies','erp_sla_targets','erp_support_tickets','erp_support_ticket_events','erp_support_messages','erp_support_attachments','erp_ticket_assignments','erp_ticket_sla_clocks','erp_managed_devices','erp_device_identifiers','erp_remote_consents','erp_remote_access_grants','erp_remote_sessions','erp_remote_session_events','erp_remote_session_artifacts'])order by c.relname;
select ok(not has_table_privilege('anon',format('public.%I',table_name),'SELECT'),format('anon não lê %s',table_name))from unnest(array['erp_support_tickets','erp_support_messages','erp_managed_devices','erp_remote_access_grants','erp_remote_sessions'])names(table_name);
select ok(has_table_privilege('authenticated',format('public.%I',table_name),'SELECT'),format('authenticated lê %s sob RLS',table_name))from unnest(array['erp_support_tickets','erp_support_messages','erp_managed_devices','erp_remote_consents','erp_remote_sessions'])names(table_name);
select ok(not has_table_privilege('authenticated',format('public.%I',table_name),'DELETE'),format('authenticated não exclui %s',table_name))from unnest(array['erp_support_tickets','erp_support_ticket_events','erp_remote_consents','erp_remote_access_grants','erp_remote_sessions'])names(table_name);
select is((select count(*)::integer from public.erp_permissions where key in('support.read','support.create','support.manage','support.assign','support.sla','remote.request','remote.connect','remote.revoke','remote.audit')),9,'nove permissões M11 existem');
select ok(not has_function_privilege('anon','public.erp_create_support_ticket(uuid,uuid,uuid,text,text,text,text,text,text)','EXECUTE'),'anon não cria ticket');select ok(has_function_privilege('authenticated','public.erp_create_support_ticket(uuid,uuid,uuid,text,text,text,text,text,text)','EXECUTE'),'authenticated cria ticket por RPC');
select ok(not has_function_privilege('anon','public.erp_issue_remote_access_grant(uuid,uuid,uuid,uuid,text[],text,text)','EXECUTE'),'anon não emite grant');select ok(has_function_privilege('authenticated','public.erp_issue_remote_access_grant(uuid,uuid,uuid,uuid,text[],text,text)','EXECUTE'),'authenticated emite grant por RPC');
select ok(not has_function_privilege('anon','public.erp_revoke_remote_access(uuid,uuid,text,text)','EXECUTE'),'anon não revoga acesso');select ok(has_function_privilege('authenticated','public.erp_revoke_remote_access(uuid,uuid,text,text)','EXECUTE'),'authenticated revoga por RPC');
select ok(exists(select 1 from pg_constraint where conname='erp_support_queues_tenant_id_code_key'),'fila única por tenant');
select ok(exists(select 1 from pg_constraint where conname='erp_sla_policies_tenant_id_code_version_key'),'SLA versionado');
select ok(exists(select 1 from pg_constraint where conname='erp_support_tickets_tenant_id_idempotency_key_key'),'ticket idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_support_ticket_events_tenant_id_idempotency_key_key'),'evento idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_support_messages_tenant_id_idempotency_key_key'),'mensagem idempotente');
select ok(exists(select 1 from pg_indexes where indexname='erp_ticket_assignments_one_active'),'atribuição ativa exclusiva');
select ok(exists(select 1 from pg_constraint where conname='erp_ticket_sla_clocks_tenant_id_ticket_id_metric_key'),'relógio SLA único');
select ok(exists(select 1 from pg_constraint where conname='erp_managed_devices_tenant_id_code_key'),'dispositivo único');
select ok(exists(select 1 from pg_constraint where conname='erp_device_identifiers_tenant_id_kind_value_hash_key'),'identificador de dispositivo único');
select ok(exists(select 1 from pg_constraint where conname='erp_remote_consents_tenant_id_idempotency_key_key'),'consentimento idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_remote_access_grants_tenant_id_token_hash_key'),'hash de token único');
select ok(exists(select 1 from pg_constraint where conname='erp_remote_access_grants_tenant_id_idempotency_key_key'),'grant idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_remote_sessions_tenant_id_grant_id_key'),'uma sessão por grant');
select ok(exists(select 1 from pg_constraint where conname='erp_remote_session_events_tenant_id_idempotency_key_key'),'evento remoto idempotente');
select ok((select prosecdef from pg_proc where oid='public.erp_create_support_ticket(uuid,uuid,uuid,text,text,text,text,text,text)'::regprocedure),'ticket security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_issue_remote_access_grant(uuid,uuid,uuid,uuid,text[],text,text)'::regprocedure),'grant security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_revoke_remote_access(uuid,uuid,text,text)'::regprocedure),'revogação security definer');
select ok(not has_function_privilege('anon','public.erp_decide_remote_consent(uuid,uuid,text,timestamptz,text)','EXECUTE'),'anon não decide consentimento');
select ok(has_function_privilege('authenticated','public.erp_decide_remote_consent(uuid,uuid,text,timestamptz,text)','EXECUTE'),'authenticated decide consentimento por RPC');
select ok((select prosecdef from pg_proc where oid='public.erp_decide_remote_consent(uuid,uuid,text,timestamptz,text)'::regprocedure),'consentimento security definer');
select ok(pg_get_functiondef('public.erp_issue_remote_access_grant(uuid,uuid,uuid,uuid,text[],text,text)'::regprocedure)like '%current_aal()%','emissão exige AAL2 inclusive para staff');
select ok(pg_get_functiondef('public.erp_revoke_remote_access(uuid,uuid,text,text)'::regprocedure)like '%current_aal()%','revogação exige AAL2 inclusive para staff');
select ok(not has_table_privilege('authenticated','public.erp_remote_consents','UPDATE'),'consentimento não aceita update direto');
select ok(not has_table_privilege('authenticated','public.erp_support_tickets','INSERT'),'ticket é criado somente por RPC');
select ok(exists(select 1 from pg_policies where schemaname='public'and tablename='erp_remote_access_grants'and policyname='erp_remote_access_grants_select'and qual like '%remote.audit%'),'grants exigem auditoria remota');
select ok(exists(select 1 from pg_constraint where conname='erp_support_attachments_message_ticket_fkey'),'anexo e mensagem pertencem ao mesmo ticket');
select ok(exists(select 1 from pg_constraint where conname='erp_remote_access_grants_consent_context_fkey'),'grant preserva contexto do consentimento');
select ok(pg_get_functiondef('public.erp_decide_remote_consent(uuid,uuid,text,timestamptz,text)'::regprocedure)like '%24 hours%','consentimento limita validade a 24 horas');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_support_ticket_events'::regclass and contype='c'),'evento recusa segredos');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_remote_access_grants'::regclass and contype='c'),'grant possui expiração válida');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_remote_session_events'::regclass and contype='c'),'sessão recusa segredos');
select * from finish();rollback;
