begin;set local role postgres;create extension if not exists pgtap with schema extensions;set local search_path=public,extensions,pgtap;select plan(100);
select ok(to_regclass(format('public.%I',table_name))is not null,format('tabela %s existe',table_name))from unnest(array['erp_tax_regimes','erp_tax_profiles','erp_tax_rules','erp_fiscal_schema_versions','erp_fiscal_series','erp_fiscal_number_reservations','erp_fiscal_documents','erp_fiscal_document_items','erp_fiscal_transmissions','erp_fiscal_events','erp_fiscal_xml_artifacts','erp_fiscal_contingencies','erp_certificate_refs','erp_fiscal_webhook_inbox'])names(table_name);
select ok(c.relrowsecurity,format('RLS ativo em %s',c.relname))from pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public'and c.relname=any(array['erp_tax_regimes','erp_tax_profiles','erp_tax_rules','erp_fiscal_schema_versions','erp_fiscal_series','erp_fiscal_number_reservations','erp_fiscal_documents','erp_fiscal_document_items','erp_fiscal_transmissions','erp_fiscal_events','erp_fiscal_xml_artifacts','erp_fiscal_contingencies','erp_certificate_refs','erp_fiscal_webhook_inbox'])order by c.relname;
select ok(not has_table_privilege('anon',format('public.%I',table_name),'SELECT'),format('anon não lê %s',table_name))from unnest(array['erp_tax_profiles','erp_tax_rules','erp_fiscal_series','erp_fiscal_documents','erp_fiscal_events','erp_fiscal_xml_artifacts','erp_certificate_refs','erp_fiscal_webhook_inbox'])names(table_name);
select ok(has_table_privilege('authenticated',format('public.%I',table_name),'SELECT'),format('authenticated lê %s sob RLS',table_name))from unnest(array['erp_tax_profiles','erp_tax_rules','erp_fiscal_series','erp_fiscal_documents','erp_fiscal_events','erp_certificate_refs','erp_fiscal_webhook_inbox','erp_fiscal_schema_versions'])names(table_name);
select ok(not has_table_privilege('authenticated',format('public.%I',table_name),'INSERT'),format('authenticated não insere diretamente em %s',table_name))from unnest(array['erp_tax_profiles','erp_fiscal_series','erp_fiscal_documents','erp_fiscal_events','erp_certificate_refs'])names(table_name);
select is((select count(*)::integer from public.erp_permissions where key in('fiscal.read','fiscal.issue','fiscal.cancel','fiscal.configure','fiscal.certificate.manage','fiscal.audit')),6,'seis permissões M13 existem');
select ok(not has_function_privilege('anon','public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)','EXECUTE'),'anon não reserva número');select ok(has_function_privilege('authenticated','public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)','EXECUTE'),'authenticated reserva por RPC');
select ok(not has_function_privilege('anon','public.erp_create_fiscal_document(uuid,uuid,uuid,uuid,text,jsonb,jsonb,timestamptz,text)','EXECUTE'),'anon não cria documento');select ok(has_function_privilege('authenticated','public.erp_create_fiscal_document(uuid,uuid,uuid,uuid,text,jsonb,jsonb,timestamptz,text)','EXECUTE'),'authenticated cria por RPC');
select ok(not has_function_privilege('anon','public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)','EXECUTE'),'anon não transiciona');select ok(has_function_privilege('authenticated','public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)','EXECUTE'),'authenticated transiciona por RPC');
select ok(not has_function_privilege('authenticated','public.erp_ingest_fiscal_provider_event(uuid,text,text,text,text,timestamptz)','EXECUTE'),'authenticated não ingere webhook');select ok(has_function_privilege('service_role','public.erp_ingest_fiscal_provider_event(uuid,text,text,text,text,timestamptz)','EXECUTE'),'broker ingere webhook');
select ok(not has_function_privilege('service_role','public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)','EXECUTE'),'broker não reserva numeração humana');
select ok(not has_function_privilege('service_role','public.erp_create_fiscal_document(uuid,uuid,uuid,uuid,text,jsonb,jsonb,timestamptz,text)','EXECUTE'),'broker não cria documento em nome do operador');
select ok(has_function_privilege('service_role','public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)','EXECUTE'),'broker pode processar estados técnicos');
select ok((select prosecdef from pg_proc where oid='public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)'::regprocedure),'reserva security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_create_fiscal_document(uuid,uuid,uuid,uuid,text,jsonb,jsonb,timestamptz,text)'::regprocedure),'criação security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)'::regprocedure),'transição security definer');
select ok((select prosecdef from pg_proc where oid='public.erp_ingest_fiscal_provider_event(uuid,text,text,text,text,timestamptz)'::regprocedure),'webhook security definer');
select ok(exists(select 1 from pg_constraint where conname='uq_fiscal_series_context'),'série única por contexto');
select ok(exists(select 1 from pg_constraint where conname='erp_fiscal_number_reservations_tenant_id_series_id_number_key'),'número reservado uma vez');
select ok(exists(select 1 from pg_constraint where conname='erp_fiscal_number_reservations_tenant_id_idempotency_key_key'),'reserva idempotente');
select ok(exists(select 1 from pg_constraint where conname='uq_fiscal_document_number'),'documento único por numeração');
select ok(exists(select 1 from pg_constraint where conname='erp_fiscal_documents_tenant_id_idempotency_key_key'),'documento idempotente');
select ok(exists(select 1 from pg_constraint where conname='erp_fiscal_documents_tenant_id_reservation_id_key'),'reserva usada uma vez');
select ok(exists(select 1 from pg_constraint where conname='erp_fiscal_events_tenant_id_idempotency_key_key'),'evento idempotente');
select ok(exists(select 1 from pg_constraint where conname='uq_fiscal_webhook_event'),'webhook deduplicado');
select ok(exists(select 1 from pg_constraint where conname='uq_certificate_ref_thumbprint'),'referência A1 única');
select ok(exists(select 1 from pg_constraint where conname='erp_fiscal_contingencies_tenant_id_document_id_key'),'uma contingência ativa por documento');
select ok(pg_get_functiondef('public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)'::regprocedure)like '%for update%','reserva bloqueia série');
select ok(pg_get_functiondef('public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)'::regprocedure)like '%current_aal()%','reserva exige AAL2');
select ok(pg_get_functiondef('public.erp_create_fiscal_document(uuid,uuid,uuid,uuid,text,jsonb,jsonb,timestamptz,text)'::regprocedure)like '%secret field forbidden%','criação bloqueia segredos');
select ok(pg_get_functiondef('public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)'::regprocedure)like '%invalid state transition%','transição usa máquina de estados');
select ok(pg_get_functiondef('public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)'::regprocedure)like '%aal2 required%','cancelamento exige AAL2');
select ok(pg_get_functiondef('public.erp_ingest_fiscal_provider_event(uuid,text,text,text,text,timestamptz)'::regprocedure)like '%broker only%','webhook somente broker');
select ok(exists(select 1 from pg_policies where schemaname='public'and tablename='erp_fiscal_documents'and qual like '%fiscal.read%'),'documentos exigem leitura fiscal');
select ok(exists(select 1 from pg_policies where schemaname='public'and tablename='erp_fiscal_events'and qual like '%fiscal.audit%'),'eventos exigem auditoria');
select ok(exists(select 1 from pg_policies where schemaname='public'and tablename='erp_certificate_refs'and qual like '%fiscal.certificate.manage%'),'certificados exigem gestão específica');
select ok(exists(select 1 from pg_policies where schemaname='public'and tablename='erp_fiscal_webhook_inbox'and qual like '%fiscal.audit%'),'webhooks exigem auditoria');
select ok(exists(select 1 from pg_policies where schemaname='public'and tablename='erp_fiscal_schema_versions'and qual='true'),'schemas oficiais são catálogo legível');
select ok(to_regclass('public.erp_fiscal_transmissions_provider_document_unique')is not null,'ID externo de transmissão usa índice parcial');
select ok(to_regclass('public.erp_fiscal_events_provider_event_unique')is not null,'ID externo de evento usa índice parcial');
select ok(exists(select 1 from pg_constraint where conname='erp_sales_tenant_establishment_id_unique'),'venda possui chave de estabelecimento composta');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_fiscal_documents'::regclass and pg_get_constraintdef(oid)like '%FOREIGN KEY (tenant_id, series_id, establishment_id, environment, model, series)%'),'documento preserva contexto completo da série');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_fiscal_documents'::regclass and pg_get_constraintdef(oid)like '%FOREIGN KEY (model, schema_version)%'),'documento referencia schema fiscal versionado');
select ok(exists(select 1 from pg_constraint where conrelid='public.erp_fiscal_contingencies'::regclass and pg_get_constraintdef(oid)like '%document_model%'),'contingência referencia NFC-e modelo 65');
select ok(pg_get_functiondef('public.erp_reserve_fiscal_number(uuid,uuid,text,text,integer,text)'::regprocedure)like '%fiscal production disabled%'and pg_get_functiondef('public.erp_ingest_fiscal_provider_event(uuid,text,text,text,text,timestamptz)'::regprocedure)like '%fiscal production disabled%','produção bloqueada na reserva e webhook');
select ok(pg_get_functiondef('public.erp_transition_fiscal_document(uuid,uuid,text,text,text,jsonb,text)'::regprocedure)like '%event and status mismatch%','evento deve corresponder ao estado');
select is((select count(*)::integer from public.erp_fiscal_documents),0,'zero documentos fiscais');
select is((select count(*)::integer from public.erp_fiscal_events),0,'zero eventos fiscais');
select is((select count(*)::integer from public.erp_fiscal_transmissions),0,'zero transmissões');
select is((select count(*)::integer from public.erp_fiscal_xml_artifacts),0,'zero XMLs/artefatos');
select is((select count(*)::integer from public.erp_certificate_refs),0,'zero certificados/referências');
select is((select count(*)::integer from public.erp_fiscal_webhook_inbox),0,'zero webhooks');
select * from finish();rollback;
