begin;
set local role postgres;
create extension if not exists pgtap with schema extensions;
set local search_path=public,extensions,pgtap;
select plan(60);
select has_table('public','erp_capability_catalog','catalogo canonico existe');
select has_table('public','erp_tenant_capabilities','entitlements canonicos existem');
select has_table('public','erp_tenant_capability_exceptions','excecoes existem');
select has_function('public','erp_set_tenant_capability',array['uuid','text','text','text','integer','text','timestamp with time zone','timestamp with time zone'],'setter existe');
select has_function('public','erp_resolve_tenant_capabilities',array['uuid','timestamp with time zone'],'resolver existe');
select has_function('public','erp_revoke_capability_exception',array['uuid','uuid','timestamp with time zone'],'revogador existe');
select has_column('public','erp_capability_catalog','risk_level','catalogo possui risco');
select has_column('public','erp_tenant_capabilities','source','entitlement possui origem');
select has_column('public','erp_tenant_capabilities','contract_version','entitlement possui versao');
select has_column('public','erp_tenant_capabilities','evidence_hash','entitlement possui evidencia');
select has_column('public','erp_tenant_capability_exceptions','approval_ref','excecao possui aprovacao opaca');
select has_column('public','erp_tenant_capability_exceptions','expires_at','excecao possui expiracao');
select has_column('public','erp_tenant_capability_exceptions','status','excecao possui status');
select ok((select relrowsecurity from pg_class where oid='public.erp_capability_catalog'::regclass),'RLS catalogo');
select ok((select relrowsecurity from pg_class where oid='public.erp_tenant_capabilities'::regclass),'RLS entitlement');
select ok((select relrowsecurity from pg_class where oid='public.erp_tenant_capability_exceptions'::regclass),'RLS excecao');
select ok((select count(*)from public.erp_capability_catalog)>=24,'catalogo preservado e ampliado');
select ok(exists(select 1 from public.erp_capability_catalog where key='device.agent'and risk_level='critical'),'agente local catalogado');
select is((select count(*)from public.erp_capability_catalog where risk_level='critical'),4::bigint,'quatro capacidades criticas');
select ok(exists(select 1 from public.erp_permissions where key='capabilities.read'),'permissao leitura');
select ok(exists(select 1 from public.erp_permissions where key='capabilities.manage'),'permissao gestao preservada');
insert into public.tenants(id,nome,slug,vertical)values('16000000-0000-4000-8000-000000000001','SYNTHETIC M16G3 A','m16-g3-synthetic-a','synthetic-me'),('16000000-0000-4000-8000-000000000002','SYNTHETIC M16G3 B','m16-g3-synthetic-b','synthetic-ltda');
insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash,starts_at)values('16000000-0000-4000-8000-000000000001','sales.orders','active','blueprint',1,repeat('a',64),'2026-01-01T00:00:00Z'),('16000000-0000-4000-8000-000000000001','finance','active','contract',1,repeat('b',64),'2026-01-01T00:00:00Z'),('16000000-0000-4000-8000-000000000002','fiscal','active','contract',1,repeat('c',64),'2026-01-01T00:00:00Z');
insert into public.erp_tenant_capability_exceptions(tenant_id,capability_key,effect,reason_hash,approval_ref,effective_from,expires_at)values('16000000-0000-4000-8000-000000000001','finance','deny',repeat('d',64),'approval:sha256:'||repeat('1',64),'2026-01-01T00:00:00Z','2027-01-01T00:00:00Z'),('16000000-0000-4000-8000-000000000001','inventory.stock','allow',repeat('e',64),'approval:sha256:'||repeat('2',64),'2026-01-01T00:00:00Z','2027-01-01T00:00:00Z');
select is((select count(*)from public.tenants where slug like'm16-g3-synthetic-%'),2::bigint,'dois tenants sinteticos');
select is((select count(*)from public.erp_tenant_capabilities where tenant_id='16000000-0000-4000-8000-000000000001'),2::bigint,'entitlements isolados A');
select is((select count(*)from public.erp_tenant_capabilities where tenant_id='16000000-0000-4000-8000-000000000002'),1::bigint,'entitlements isolados B');
select is((select count(*)from public.erp_tenant_capability_exceptions where tenant_id='16000000-0000-4000-8000-000000000001'),2::bigint,'excecoes isoladas A');
select is((select status from public.erp_tenant_capabilities where capability_key='finance'),'active','status contratual');
select is((select source from public.erp_tenant_capabilities where capability_key='finance'),'contract','origem contratual');
select is((select effect from public.erp_tenant_capability_exceptions where capability_key='finance'),'deny','negacao persistida');
select is((select effect from public.erp_tenant_capability_exceptions where capability_key='inventory.stock'),'allow','permissao persistida');
select throws_ok($$insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash)values('16000000-0000-4000-8000-000000000001','unknown','active','contract',1,repeat('f',64))$$,'23503',null,'capacidade desconhecida recusada');
select throws_ok($$insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash)values('16000000-0000-4000-8000-000000000001','sales.pos','root','contract',1,repeat('f',64))$$,'23514',null,'status invalido recusado');
select throws_ok($$insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash)values('16000000-0000-4000-8000-000000000001','sales.pos','active','root',1,repeat('f',64))$$,'23514',null,'origem invalida recusada');
select throws_ok($$insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash)values('16000000-0000-4000-8000-000000000001','sales.pos','active','contract',0,repeat('f',64))$$,'23514',null,'versao invalida recusada');
select throws_ok($$insert into public.erp_tenant_capability_exceptions(tenant_id,capability_key,effect,reason_hash,approval_ref,effective_from,expires_at)values('16000000-0000-4000-8000-000000000001','sales.pos','root',repeat('f',64),'approval:sha256:'||repeat('3',64),now(),now()+interval'1 day')$$,'23514',null,'efeito invalido recusado');
select throws_ok($$insert into public.erp_tenant_capability_exceptions(tenant_id,capability_key,effect,reason_hash,approval_ref,effective_from,expires_at)values('16000000-0000-4000-8000-000000000001','sales.pos','deny',repeat('f',64),'invalid',now(),now()+interval'1 day')$$,'23514',null,'aprovacao invalida recusada');
select throws_ok($$insert into public.erp_tenant_capability_exceptions(tenant_id,capability_key,effect,reason_hash,approval_ref,effective_from,expires_at)values('16000000-0000-4000-8000-000000000001','sales.pos','deny',repeat('f',64),'approval:sha256:'||repeat('4',64),now(),now())$$,'23514',null,'expiracao invalida recusada');
select throws_ok($$insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash)values('16000000-0000-4000-8000-000000000001','finance','active','contract',2,repeat('f',64))$$,'23505',null,'entitlement duplicado recusado');
select is((select count(*)from pg_policies where schemaname='public'and tablename='erp_capability_catalog'),1::bigint,'policy catalogo preservada');
select is((select count(*)from pg_policies where schemaname='public'and tablename='erp_tenant_capabilities'),1::bigint,'policy entitlement preservada');
select is((select count(*)from pg_policies where schemaname='public'and tablename='erp_tenant_capability_exceptions'),1::bigint,'policy excecao criada');
select ok(has_table_privilege('authenticated','public.erp_capability_catalog','SELECT'),'authenticated le catalogo');
select ok(has_table_privilege('authenticated','public.erp_tenant_capabilities','SELECT'),'authenticated le entitlement sob RLS');
select ok(has_table_privilege('authenticated','public.erp_tenant_capability_exceptions','SELECT'),'authenticated le excecao sob RLS');
select ok(not has_table_privilege('authenticated','public.erp_tenant_capability_exceptions','INSERT'),'authenticated nao insere excecao');
select ok(not has_table_privilege('authenticated','public.erp_tenant_capabilities','UPDATE'),'authenticated nao altera entitlement');
select ok(not has_table_privilege('service_role','public.erp_tenant_capabilities','INSERT'),'service role nao insere diretamente');
select ok(not has_table_privilege('service_role','public.erp_tenant_capabilities','UPDATE'),'service role nao atualiza diretamente');
select ok(not has_table_privilege('service_role','public.erp_tenant_capabilities','DELETE'),'service role nao exclui entitlement');
select ok(not has_table_privilege('service_role','public.erp_capability_catalog','INSERT'),'service role nao altera catalogo');
select ok(has_function_privilege('authenticated','public.erp_resolve_tenant_capabilities(uuid,timestamp with time zone)','EXECUTE'),'authenticated executa resolver');
select ok(not has_function_privilege('authenticated','public.erp_set_tenant_capability(uuid,text,text,text,integer,text,timestamp with time zone,timestamp with time zone)','EXECUTE'),'authenticated nao executa setter');
select ok(not has_function_privilege('authenticated','public.erp_revoke_capability_exception(uuid,uuid,timestamp with time zone)','EXECUTE'),'authenticated nao revoga');
select ok(has_function_privilege('service_role','public.erp_resolve_tenant_capabilities(uuid,timestamp with time zone)','EXECUTE'),'service executa resolver');
select ok(has_function_privilege('service_role','public.erp_set_tenant_capability(uuid,text,text,text,integer,text,timestamp with time zone,timestamp with time zone)','EXECUTE'),'service executa setter');
select ok(has_function_privilege('service_role','public.erp_revoke_capability_exception(uuid,uuid,timestamp with time zone)','EXECUTE'),'service executa revogador');
set local role service_role;
select set_config('request.jwt.claim.role','service_role',true);
select is((select status from public.erp_resolve_tenant_capabilities('16000000-0000-4000-8000-000000000001','2026-08-30T12:00:00Z')where capability_key='finance'),'disabled','deny prevalece');
select is((select status from public.erp_resolve_tenant_capabilities('16000000-0000-4000-8000-000000000001','2026-08-30T12:00:00Z')where capability_key='inventory.stock'),'active','allow habilita');
select is((select status from public.erp_resolve_tenant_capabilities('16000000-0000-4000-8000-000000000001','2026-08-30T12:00:00Z')where capability_key='core.catalog'),'disabled','default deny');
select is((select public.erp_revoke_capability_exception('16000000-0000-4000-8000-000000000001',(select id from public.erp_tenant_capability_exceptions where capability_key='inventory.stock'),now())),true,'revogacao funciona');
select is((select public.erp_revoke_capability_exception('16000000-0000-4000-8000-000000000001',(select id from public.erp_tenant_capability_exceptions where capability_key='inventory.stock'),now())),false,'revogacao idempotente');
reset role;
select * from finish();
rollback;
