import { createHash, randomUUID } from 'node:crypto'
const LEGAL_PROFILES=new Set(['MEI','ME','LTDA']),MODULES=new Set(['parties','catalog','inventory','sales','cash','finance','fiscal'])
const PERMISSIONS=Object.freeze({owner:['*'],admin:['parties','catalog','inventory','sales','cash','finance'],operator:['parties','catalog','inventory','sales','cash'],finance:['finance'],viewer:[]})
const fail=code=>{throw new Error(code)},hash=value=>createHash('sha256').update(JSON.stringify(value)).digest('hex')
function assertSynthetic(value){const text=JSON.stringify(value);if(!text.includes('SYNTHETIC')||/cnpj|cpf|password|secret|certificate|csc/i.test(text))fail('REAL_OR_SECRET_DATA_FORBIDDEN')}
export class SyntheticPilotLab{
  #tenants=new Map();#memberships=new Map();#records=new Map();#events=[]
  createTenant({legalProfile,name}){if(!LEGAL_PROFILES.has(legalProfile)||!/^SYNTHETIC-/.test(name))fail('INVALID_SYNTHETIC_TENANT');const tenant=Object.freeze({id:randomUUID(),legalProfile,name,synthetic:true});this.#tenants.set(tenant.id,tenant);return tenant}
  authenticate({userId,tenantId,role,mfa=false}){if(!this.#tenants.has(tenantId))fail('TENANT_NOT_FOUND');if(!PERMISSIONS[role])fail('INVALID_ROLE');if((role==='owner'||role==='admin')&&!mfa)fail('MFA_REQUIRED');const session=Object.freeze({id:randomUUID(),userId,tenantId,role,mfa,synthetic:true});this.#memberships.set(`${userId}:${tenantId}`,role);return session}
  access(session,tenantId,module,operation='read'){if(!session||session.tenantId!==tenantId)fail('CROSS_TENANT_DENIED');if(this.#memberships.get(`${session.userId}:${tenantId}`)!==session.role)fail('MEMBERSHIP_REQUIRED');if(!MODULES.has(module))fail('UNKNOWN_MODULE');if(module==='fiscal')fail('FISCAL_FAIL_CLOSED');const allowed=PERMISSIONS[session.role];if(!(allowed.includes('*')||allowed.includes(module)))fail('PERMISSION_DENIED');return Object.freeze({tenantId,module,operation,allowed:true})}
  write(session,tenantId,module,payload,idempotencyKey){this.access(session,tenantId,module,'write');assertSynthetic(payload);if(!/^m15g2:[a-z0-9:-]+$/.test(idempotencyKey))fail('INVALID_IDEMPOTENCY_KEY');const key=`${tenantId}:${module}:${idempotencyKey}`,payloadHash=hash(payload),prior=this.#records.get(key);if(prior&&prior.payloadHash!==payloadHash)fail('IDEMPOTENCY_CONFLICT');if(prior)return Object.freeze({...prior,replayed:true});const record=Object.freeze({id:randomUUID(),tenantId,module,payloadHash,replayed:false});this.#records.set(key,record);this.#events.push(Object.freeze({tenantId,module,operation:'write',payloadHash}));return record}
  count(tenantId,module){return[...this.#records.keys()].filter(key=>key.startsWith(`${tenantId}:${module}:`)).length}
  rollback(){const removed=this.#records.size;this.#records.clear();this.#events.length=0;return Object.freeze({removed,remaining:0})}
  evidence(){return Object.freeze({tenants:this.#tenants.size,memberships:this.#memberships.size,records:this.#records.size,events:this.#events.length,remoteAccessed:false,productionAccessed:false,persisted:false})}
}
export function executeSyntheticJourney(){const lab=new SyntheticPilotLab(),tenants=['MEI','ME','LTDA'].map(profile=>lab.createTenant({legalProfile:profile,name:`SYNTHETIC-${profile}`})),pilot=tenants[1],session=lab.authenticate({userId:'SYNTHETIC-USER-OWNER',tenantId:pilot.id,role:'owner',mfa:true}),steps=[['parties',{name:'SYNTHETIC-CUSTOMER'}],['catalog',{sku:'SYNTHETIC-SKU-001'}],['inventory',{movement:'SYNTHETIC-ENTRY',quantity:10}],['sales',{sale:'SYNTHETIC-SALE-001',amountCents:1000}],['cash',{movement:'SYNTHETIC-CASH',amountCents:1000}],['finance',{title:'SYNTHETIC-RECEIVABLE',amountCents:1000}]];steps.forEach(([module,payload],index)=>lab.write(session,pilot.id,module,payload,`m15g2:${module}:${index+1}`));let crossTenantDenied=false,fiscalFailClosed=false;try{lab.access(session,tenants[2].id,'sales')}catch(error){crossTenantDenied=error.message==='CROSS_TENANT_DENIED'}try{lab.access(session,pilot.id,'fiscal')}catch(error){fiscalFailClosed=error.message==='FISCAL_FAIL_CLOSED'}const beforeRollback=lab.evidence(),rollback=lab.rollback();return Object.freeze({result:'M15_G2_SYNTHETIC_JOURNEY_OK',profiles:tenants.map(item=>item.legalProfile),modules:steps.map(item=>item[0]),crossTenantDenied,fiscalFailClosed,beforeRollback,rollback,afterRollback:lab.evidence()})}
