import test from'node:test';import assert from'node:assert/strict';import{AGGREGATE_LIMIT,createSupabaseAggregateReader}from'../src/index.mjs';
const tenant='00000000-0000-4000-8000-000000000018';
function clientFor(fixtures={},errors={}){const calls=[];return{calls,client:{from(table){calls.push(['from',table]);const chain={select(columns){calls.push(['select',table,columns]);return chain;},eq(...args){calls.push(['eq',table,...args]);return chain;},in(...args){calls.push(['in',table,...args]);return chain;},limit(value){calls.push(['limit',table,value]);return Promise.resolve({data:fixtures[table]??[],error:errors[table]??null});}};return chain;}}};}
test('limite agregado é explícito e finito',()=>assert.equal(AGGREGATE_LIMIT,5000));
test('financeiro deriva totais somente do tenant',async()=>{const{client,calls}=clientFor({erp_financial_entries:[{direction:'receivable',status:'open',principal_amount:'120.50'},{direction:'payable',status:'settled',principal_amount:20}],erp_installments:[{status:'overdue'},{status:'settled'}]});const result=await createSupabaseAggregateReader()({client,tenantId:tenant,scope:'finance'});assert.deepEqual(result,{scope:'finance',receivablePrincipal:120.5,payablePrincipal:20,openReceivablePrincipal:120.5,openPayablePrincipal:0,openInstallments:1,overdueInstallments:1});assert.equal(calls.filter(row=>row[0]==='eq'&&row[2]==='tenant_id'&&row[3]===tenant).length,2);});
test('dashboard entrega formato visual reconciliado',async()=>{const{client}=clientFor({erp_party_roles:[{party_id:'p'}],erp_catalog_items:[{id:'i'}],erp_stock_movement_items:[{quantity_delta:7},{quantity_delta:-2}],erp_sales:[{id:'s',grand_total:'150'}],erp_cash_sessions:[{id:'c'}],erp_financial_entries:[{direction:'receivable',principal_amount:100}],erp_settlement_allocations:[{allocated_amount:40,erp_settlements:{status:'confirmed'},erp_installments:{erp_financial_entries:{direction:'receivable'}}}]});const result=await createSupabaseAggregateReader()({client,tenantId:tenant,scope:'dashboard'});assert.deepEqual(result,{customers:1,products:1,stockUnits:5,salesCount:1,salesTotal:150,cashSales:50,receivables:100,settled:40,openReceivables:60,cashStatus:'open',balanced:true});});
test('dashboard bloqueia recebíveis maiores que vendas',async()=>{const{client}=clientFor({erp_sales:[{grand_total:10}],erp_financial_entries:[{direction:'receivable',principal_amount:11}]});await assert.rejects(createSupabaseAggregateReader()({client,tenantId:tenant,scope:'dashboard'}),/INVALID_PERSISTENCE_RESPONSE/);});
test('escopo desconhecido falha fechado sem consulta',async()=>{const{client,calls}=clientFor();await assert.rejects(createSupabaseAggregateReader()({client,tenantId:tenant,scope:'other'}),/ADAPTER_READ_BLOCKED/);assert.equal(calls.length,0);});
test('agregador exportado também recusa tenant inválido',async()=>{const{client,calls}=clientFor();await assert.rejects(createSupabaseAggregateReader()({client,tenantId:'invalid',scope:'finance'}),/TENANT_UNRESOLVED/);assert.equal(calls.length,0);});
test('erro da origem é sanitizado',async()=>{const{client}=clientFor({}, {erp_financial_entries:{code:'42501',message:'secret'}});await assert.rejects(createSupabaseAggregateReader()({client,tenantId:tenant,scope:'finance'}),error=>error.code==='42501'&&error.message==='aggregate read failed');});
test('janela cheia bloqueia total possivelmente truncado',async()=>{const{client}=clientFor({erp_financial_entries:Array.from({length:AGGREGATE_LIMIT},()=>({status:'open'}))});await assert.rejects(createSupabaseAggregateReader()({client,tenantId:tenant,scope:'finance'}),/AGGREGATE_LIMIT_EXCEEDED/);});
