import test from 'node:test'
import assert from 'node:assert/strict'
import { CAPABILITIES, PLAN_BLUEPRINTS, executeSyntheticCapabilitySimulation, isCapabilityEnabled, resolveCapabilities, validateCapabilityManifest } from '../src/index.mjs'
const manifest=(legalProfile='ME',exceptions=[])=>({version:1,tenantId:`SYNTHETIC-TENANT-${legalProfile}`,legalProfile,exceptions})
const exception=(overrides={})=>({id:'SYNTHETIC-EX-001',capability:'finance',effect:'deny',reason:'SYNTHETIC-SCOPE',approvedBy:'SYNTHETIC-APPROVER-OWNER',expiresAt:'2027-01-01T00:00:00.000Z',...overrides})
test('catálogo canônico não possui duplicidade',()=>assert.equal(new Set(CAPABILITIES).size,CAPABILITIES.length))
test('blueprints MEI ME LTDA existem',()=>assert.deepEqual(Object.keys(PLAN_BLUEPRINTS),['MEI','ME','LTDA']))
test('MEI inicia sem estoque',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('MEI')),'inventory'),false))
test('ME inicia com estoque',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('ME')),'inventory'),true))
test('LTDA inicia com fiscal',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('LTDA')),'fiscal'),true))
test('negação ativa remove capacidade',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('ME',[exception()])),'finance'),false))
test('negação prevalece sobre permissão em qualquer ordem',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('MEI',[exception({id:'SYNTHETIC-EX-001',effect:'deny',capability:'inventory'}),exception({id:'SYNTHETIC-EX-002',effect:'allow',capability:'inventory'})])),'inventory'),false))
test('permissão ativa adiciona capacidade',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('MEI',[exception({effect:'allow',capability:'inventory'})])),'inventory'),true))
test('exceção expirada não altera blueprint',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest('ME',[exception({expiresAt:'2026-01-01T00:00:00.000Z'})])),'finance'),true))
test('capacidade desconhecida falha fechada',()=>assert.equal(isCapabilityEnabled(resolveCapabilities(manifest()),'unknown'),false))
test('perfil desconhecido é recusado',()=>assert.throws(()=>validateCapabilityManifest(manifest('SA')),/UNKNOWN_LEGAL_PROFILE/))
test('versão desconhecida é recusada',()=>assert.throws(()=>validateCapabilityManifest({...manifest(),version:2}),/UNSUPPORTED_MANIFEST_VERSION/))
test('tenant real é recusado',()=>assert.throws(()=>validateCapabilityManifest({...manifest(),tenantId:'tenant-real'}),/REAL_OR_SECRET_DATA_FORBIDDEN|INVALID_SYNTHETIC_TENANT/))
test('identificador duplicado é recusado',()=>assert.throws(()=>validateCapabilityManifest(manifest('ME',[exception(),exception()])),/INVALID_EXCEPTION_ID/))
test('capacidade inválida na exceção é recusada',()=>assert.throws(()=>validateCapabilityManifest(manifest('ME',[exception({capability:'root'})])),/UNKNOWN_CAPABILITY/))
test('aprovador sintético é obrigatório',()=>assert.throws(()=>validateCapabilityManifest(manifest('ME',[exception({approvedBy:'owner'})])),/INVALID_EXCEPTION_APPROVER/))
test('hash é determinístico',()=>assert.equal(resolveCapabilities(manifest()).auditHash,resolveCapabilities(manifest()).auditHash))
test('hash muda quando o contrato muda',()=>assert.notEqual(resolveCapabilities(manifest('ME')).auditHash,resolveCapabilities(manifest('LTDA')).auditHash))
test('resolução não acessa remoto ou produção',()=>{const result=resolveCapabilities(manifest());assert.equal(result.remoteAccessed,false);assert.equal(result.productionAccessed,false)})
test('simulador emite marcador oficial',()=>assert.equal(executeSyntheticCapabilitySimulation().result,'M16_G1_CAPABILITY_CONTRACT_OK'))
