'use server';
import { revalidatePath } from 'next/cache';import { visualPersistenceClient } from '@/features/persistence/selected';import { partyAddressSchema, partyContactSchema, partyDocumentSchema, partySchema } from './validations';
export type PartyActionState={error:string|null;success:boolean};
export async function createPartyAction(_:PartyActionState,formData:FormData):Promise<PartyActionState>{const parsed=partySchema.safeParse({kind:formData.get('kind'),legal_name:formData.get('legal_name'),trade_name:formData.get('trade_name')||undefined,tax_id:String(formData.get('tax_id')??'').replace(/\D/g,''),role:formData.get('role')});if(!parsed.success)return{error:parsed.error.issues[0]?.message??'Dados inválidos.',success:false};try{const result=await visualPersistenceClient.execute('party.create',{kind:parsed.data.kind,legalName:parsed.data.legal_name,tradeName:parsed.data.trade_name??'',taxId:parsed.data.tax_id??'',role:parsed.data.role});if(!result.ok)return{error:result.error.message,success:false};revalidatePath('/cadastros');return{error:null,success:true}}catch{return{error:'Não foi possível cadastrar nesta sessão.',success:false}}}

// M20-G3 — abas Documentos/Contatos/Endereços, sempre anexadas a uma pessoa já criada.
export async function addPartyDocumentAction(_:PartyActionState,formData:FormData):Promise<PartyActionState>{const parsed=partyDocumentSchema.safeParse({party_id:formData.get('party_id'),type:formData.get('type'),number:formData.get('number'),issuer:formData.get('issuer')||undefined,issued_at:formData.get('issued_at')||undefined,expires_at:formData.get('expires_at')||undefined});if(!parsed.success)return{error:parsed.error.issues[0]?.message??'Documento inválido.',success:false};try{const result=await visualPersistenceClient.execute('party.document.add',{partyId:parsed.data.party_id,type:parsed.data.type,number:parsed.data.number,issuer:parsed.data.issuer??'',issuedAt:parsed.data.issued_at??'',expiresAt:parsed.data.expires_at??''});if(!result.ok)return{error:result.error.message,success:false};revalidatePath('/cadastros');return{error:null,success:true}}catch{return{error:'Não foi possível adicionar o documento nesta sessão.',success:false}}}

export async function addPartyContactAction(_:PartyActionState,formData:FormData):Promise<PartyActionState>{const parsed=partyContactSchema.safeParse({party_id:formData.get('party_id'),type:formData.get('type'),value:formData.get('value'),label:formData.get('label')||undefined,is_primary:formData.get('is_primary')==='on'});if(!parsed.success)return{error:parsed.error.issues[0]?.message??'Contato inválido.',success:false};try{const result=await visualPersistenceClient.execute('party.contact.add',{partyId:parsed.data.party_id,type:parsed.data.type,value:parsed.data.value,label:parsed.data.label??'',isPrimary:parsed.data.is_primary});if(!result.ok)return{error:result.error.message,success:false};revalidatePath('/cadastros');return{error:null,success:true}}catch{return{error:'Não foi possível adicionar o contato nesta sessão.',success:false}}}

export async function addPartyAddressAction(_:PartyActionState,formData:FormData):Promise<PartyActionState>{const parsed=partyAddressSchema.safeParse({party_id:formData.get('party_id'),type:formData.get('type'),postal_code:formData.get('postal_code')||undefined,street:formData.get('street'),number:formData.get('number')||undefined,complement:formData.get('complement')||undefined,district:formData.get('district')||undefined,city:formData.get('city'),state_code:formData.get('state_code')||undefined,is_primary:formData.get('is_primary')==='on'});if(!parsed.success)return{error:parsed.error.issues[0]?.message??'Endereço inválido.',success:false};try{const result=await visualPersistenceClient.execute('party.address.add',{partyId:parsed.data.party_id,type:parsed.data.type,postalCode:parsed.data.postal_code??'',street:parsed.data.street,number:parsed.data.number??'',complement:parsed.data.complement??'',district:parsed.data.district??'',city:parsed.data.city,stateCode:parsed.data.state_code??'',isPrimary:parsed.data.is_primary});if(!result.ok)return{error:result.error.message,success:false};revalidatePath('/cadastros');return{error:null,success:true}}catch{return{error:'Não foi possível adicionar o endereço nesta sessão.',success:false}}}
