import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('../../../', import.meta.url));
const read = path => readFileSync(`${root}${path}`, 'utf8');
const migration = read('supabase/migrations/0033_m17_persistent_journey.sql');
const preflight = read('supabase/preflight/0033_m17_persistent_journey_preflight.sql');
const rollback = read('supabase/rollback/0033_m17_persistent_journey_rollback.sql');
const pgtap = read('supabase/tests/0033_m17_persistent_journey.test.sql');
const rpcNames = ['create_party','create_catalog_item','receive_inventory','open_cash','complete_sale','settle_receivable','close_cash'];

test('migration 0033 possui transação explícita', () => assert.match(migration, /^--[^\n]+\nbegin;[\s\S]+commit;\s*$/));
test('inbox transacional é tenant scoped', () => assert.match(migration, /create table public\.erp_command_receipts[\s\S]+tenant_id uuid not null/));
test('inbox tem unicidade por tenant comando e request', () => assert.match(migration, /unique \(tenant_id,command_type,request_id\)/));
test('hash exige sha256 hexadecimal', () => assert.match(migration, /payload_hash ~ '\^\[a-f0-9\]\{64\}\$'/));
test('receipt terminal exige resultado e horário', () => assert.match(migration, /status='succeeded' and result_json is not null and completed_at is not null/));
test('RLS está habilitada no inbox', () => assert.match(migration, /alter table public\.erp_command_receipts enable row level security/));
test('authenticated não recebe acesso direto ao inbox', () => assert.match(migration, /revoke all on table public\.erp_command_receipts from public,anon,authenticated/));
test('claim usa lock transacional', () => assert.match(migration, /erp_claim_command_v1[\s\S]+pg_advisory_xact_lock/));
test('claim compara hash canônico calculado em replay', () => assert.match(migration, /v\.payload_hash<>v_computed_hash/));
test('claim recalcula SHA-256 do JSONB no banco', () => assert.match(migration, /extensions\.digest\(convert_to\(v_payload_text,'UTF8'\),'sha256'\)/));
test('hash informado não é autoridade de persistência', () => assert.match(migration, /values\(p_tenant_id,p_command_type,p_request_id,v_computed_hash,auth\.uid\(\)\)/));
test('payload tem limite e triagem de segredos', () => { assert.match(migration, /octet_length\(v_payload_text\)>65536/); assert.match(migration, /unsafe command payload/); });
test('estoque exige item rastreável e local ativo', () => assert.match(migration, /i\.track_inventory and i\.status='active'[\s\S]+l\.active/));
test('venda a prazo projeta recebível e parcela na mesma RPC', () => { assert.match(migration, /pm\.kind='store_credit'/); assert.match(migration, /insert into public\.erp_financial_entries/); assert.match(migration, /insert into public\.erp_installments/); });
test('projeção financeira usa identidade e valor autoritativos do banco', () => assert.match(migration, /v_sale\.customer_id is null[\s\S]+v_credit<>v_sale\.grand_total/));
test('claim recusa comando ainda processando', () => assert.match(migration, /command already processing/));
test('sete RPCs versionadas existem', () => assert.equal(rpcNames.every(name => migration.includes(`erp_command_${name}_v1`)), true));
test('sete RPCs verificam autorização', () => assert.equal((migration.match(/perform public\.erp_require_command_access_v1/g) ?? []).length, 7));
test('sete RPCs reivindicam receipt', () => assert.equal((migration.match(/c:=public\.erp_claim_command_v1/g) ?? []).length, 7));
test('sete RPCs completam receipt', () => assert.equal((migration.match(/return public\.erp_complete_command_v1/g) ?? []).length, 7));
test('helpers não são executáveis por authenticated', () => assert.match(migration, /revoke execute on function public\.erp_require_command_access_v1[\s\S]+from public,anon,authenticated/));
test('RPCs recusam anon', () => assert.match(migration, /revoke execute on function public\.erp_command_create_party_v1[\s\S]+from public,anon/));
test('preflight cobre baseline e ausência da 0033', () => { assert.match(preflight, /required baseline RPC missing/); assert.match(preflight, /0033 already present/); });
test('preflight possui marcador determinístico', () => assert.match(preflight, /M17_0033_PREFLIGHT_OK/));
test('rollback remove sete RPCs helpers e tabela', () => { assert.equal(rpcNames.every(name => rollback.includes(`drop function if exists public.erp_command_${name}_v1`)), true); assert.match(rollback, /drop table if exists public\.erp_command_receipts/); });
test('pgTAP declara 96 asserções e rollback', () => { assert.match(pgtap, /select plan\(96\)/); assert.match(pgtap, /select\*from finish\(\);rollback;/); });
test('nenhum arquivo executa acesso remoto', () => assert.doesNotMatch(migration + preflight + rollback + pgtap, /supabase\s+(db|link|login)|https?:\/\//i));
