import test from 'node:test';
import assert from 'node:assert/strict';
import { BASELINE_MIGRATIONS, CONCURRENCY_POLICY, DATABASE_INVARIANTS, PERSISTENCE_TABLE_CONTRACT, RELEASE_GATES, ROLLBACK_POLICY, RPC_CONTRACTS, TRANSACTION_PROTOCOL, validatePostgresPersistenceContract } from '../src/postgres-persistence-contract.mjs';

test('contrato cobre os sete comandos', () => assert.equal(Object.keys(RPC_CONTRACTS).length, 7));
test('validador aprova contrato integral', () => assert.deepEqual(validatePostgresPersistenceContract().findings, []));
test('todas as RPCs são versionadas', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.rpc.endsWith('_v1')), true));
test('todas as RPCs usam search_path vazio', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.security === 'security-definer-search-path-empty'), true));
test('todas exigem permissão e capacidade', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.permission && row.capability), true));
test('tenant vem do host resolvido pelo servidor', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.tenantSource === 'server-resolved-host'), true));
test('ator vem de auth uid', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.actorSource === 'auth.uid'), true));
test('command receipt é primeiro lock de toda RPC', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.locks[0] === 'command-receipt'), true));
test('toda RPC escreve command receipt', () => assert.equal(Object.values(RPC_CONTRACTS).every(row => row.writes.includes('erp_command_receipts')), true));
test('todas as tabelas são tenant scoped com RLS', () => assert.equal(Object.values(PERSISTENCE_TABLE_CONTRACT).every(row => row.tenantScoped && row.rls), true));
test('inbox tem unicidade por tenant comando e request', () => assert.ok(PERSISTENCE_TABLE_CONTRACT.commandReceipts.constraints.includes('unique:tenant_id+command_type+request_id')));
test('inbox compara hash sha256', () => assert.ok(PERSISTENCE_TABLE_CONTRACT.commandReceipts.constraints.includes('check:payload_hash_sha256')));
test('protocolo deriva valores no servidor antes da escrita', () => assert.ok(TRANSACTION_PROTOCOL.includes('derive-prices-totals-balances-and-tenant-on-server')));
test('protocolo reconcilia antes do commit', () => assert.ok(TRANSACTION_PROTOCOL.indexOf('reconcile-invariants') < TRANSACTION_PROTOCOL.indexOf('commit-or-rollback-entire-rpc')));
test('venda persiste estoque caixa e financeiro na mesma RPC', () => assert.deepEqual(['erp_stock_movements', 'erp_cash_movements', 'erp_financial_entries'].every(table => RPC_CONTRACTS['sale.complete'].writes.includes(table)), true));
test('liquidação bloqueia parcelas em ordem', () => assert.ok(RPC_CONTRACTS['finance.receivable.settle'].locks.includes('installment-keys-ordered')));
test('política impede baixa superior ao saldo', () => assert.ok(DATABASE_INVARIANTS.includes('settlement-never-exceeds-open-balance')));
test('dinheiro no banco e centavos na fronteira são explícitos', () => assert.ok(DATABASE_INVARIANTS.includes('money-uses-numeric-19-4-in-database-and-integer-cents-at-boundary')));
test('locks possuem ordem canônica', () => assert.equal(CONCURRENCY_POLICY.deadlockPrevention, 'sort-lock-keys-lexicographically'));
test('retry distribuído é limitado e nunca automático no navegador', () => assert.deepEqual([CONCURRENCY_POLICY.maxServerRetries, CONCURRENCY_POLICY.browserRetriesWrites], [2, false]));
test('rollback cobre toda RPC sem efeitos externos', () => assert.deepEqual([ROLLBACK_POLICY.boundary, ROLLBACK_POLICY.externalSideEffectsAllowed], ['entire-rpc', false]));
test('outbox é obrigatório antes de efeitos futuros', () => assert.equal(ROLLBACK_POLICY.outboxRequiredBeforeFutureExternalEffects, true));
test('baseline reutiliza migrations existentes sem sobrescrever', () => assert.deepEqual(BASELINE_MIGRATIONS.map(row => row.version), ['0021', '0022', '0023', '0024', '0032']));
test('promoção exige rollback pgTAP concorrência e reconciliação', () => assert.equal(['transactional-rollback-validation', 'pgtap-concurrency', 'post-apply-reconciliation'].every(gate => RELEASE_GATES.includes(gate)), true));
test('artefato confirma ausência de migration e remoto', () => { const result = validatePostgresPersistenceContract(); assert.equal(result.migrationCreated || result.remoteAccessed || result.productionAccessed, false); });
