import {createHash} from 'node:crypto';
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i,SHA256=/^[0-9a-f]{64}$/;
const SOURCES=new Set(['sqlserver-backup','sqlserver-readonly','csv-export','json-export']),DOMAINS=new Set(['customers','suppliers','employees','products','stock','sales','cash','receivables','payables','fiscal-metadata']),FORBIDDEN=/password|senha|secret|token|service.?role|private.?key|pfx|p12|csc|connection.?string/i;
const fail=code=>{throw new Error(code)},stable=value=>Array.isArray(value)?value.map(stable):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,stable(value[key])])):value;
export const canonicalHash=value=>createHash('sha256').update(JSON.stringify(stable(value))).digest('hex');
function rejectSecrets(value,path='root'){if(Array.isArray(value))return value.forEach((item,index)=>rejectSecrets(item,`${path}[${index}]`));if(value&&typeof value==='object')for(const[key,item]of Object.entries(value)){if(FORBIDDEN.test(key))fail(`FORBIDDEN_FIELD:${path}.${key}`);rejectSecrets(item,`${path}.${key}`)}}
function rejectCrossTenant(value,tenantId){if(Array.isArray(value))return value.forEach(item=>rejectCrossTenant(item,tenantId));if(value&&typeof value==='object')for(const[key,item]of Object.entries(value)){if(key==='tenantId'&&item!==tenantId)fail('PAYLOAD_TENANT_MISMATCH');rejectCrossTenant(item,tenantId)}}
export function validateSourceManifest(manifest={}){rejectSecrets(manifest);if(manifest.contractVersion!=='1.0')fail('UNSUPPORTED_CONTRACT');for(const field of['manifestId','tenantId','extractionId'])if(!UUID.test(manifest[field]??''))fail(`INVALID_${field.toUpperCase()}`);if(!SOURCES.has(manifest.sourceType))fail('INVALID_SOURCE_TYPE');if(!SHA256.test(manifest.sourceSha256??''))fail('INVALID_SOURCE_HASH');if(!/^legacy-[a-z0-9.-]+$/.test(manifest.schemaVersion??''))fail('INVALID_SCHEMA_VERSION');if(!Number.isFinite(Date.parse(manifest.capturedAt??'')))fail('INVALID_CAPTURE_TIME');if(manifest.immutable!==true)fail('SOURCE_MUST_BE_IMMUTABLE');if(manifest.containsRealData!==false)fail('REAL_DATA_FORBIDDEN');if('sourcePath'in manifest||'credentials'in manifest)fail('SOURCE_LOCATION_FORBIDDEN');return Object.freeze({...manifest,manifestHash:canonicalHash(manifest)})}
export function validateCanonicalBatch(batch={},manifest){rejectSecrets(batch);if(!manifest?.manifestHash)fail('VALIDATED_MANIFEST_REQUIRED');for(const field of['batchId','tenantId'])if(!UUID.test(batch[field]??''))fail(`INVALID_${field.toUpperCase()}`);if(batch.tenantId!==manifest.tenantId)fail('TENANT_MISMATCH');if(batch.manifestHash!==manifest.manifestHash)fail('MANIFEST_HASH_MISMATCH');if(!DOMAINS.has(batch.domain))fail('INVALID_DOMAIN');if(!Number.isInteger(batch.sequence)||batch.sequence<1)fail('INVALID_SEQUENCE');if(!Array.isArray(batch.records)||batch.records.length===0||batch.records.length>1000)fail('INVALID_RECORDS');if(!batch.expectedMetrics||!Number.isInteger(batch.expectedMetrics.recordCount)||!Number.isInteger(batch.expectedMetrics.amountCents)||batch.expectedMetrics.amountCents<0)fail('INVALID_EXPECTED_METRICS');const keys=new Set();let amountCents=0;for(const record of batch.records){if(!/^canonical:[a-z0-9:-]{8,200}$/.test(record.canonicalKey??''))fail('INVALID_CANONICAL_KEY');if(keys.has(record.canonicalKey))fail('DUPLICATE_KEY_IN_BATCH');keys.add(record.canonicalKey);if(!SHA256.test(record.sourceKeyHash??''))fail('INVALID_SOURCE_KEY_HASH');if(!record.payload||typeof record.payload!=='object'||Array.isArray(record.payload))fail('INVALID_PAYLOAD');rejectCrossTenant(record.payload,batch.tenantId);const amount=record.payload.amountCents??0;if(!Number.isInteger(amount)||amount<0)fail('INVALID_AMOUNT');amountCents+=amount}if(batch.expectedMetrics.recordCount!==batch.records.length)fail('RECONCILIATION_COUNT_MISMATCH');if(batch.expectedMetrics.amountCents!==amountCents)fail('RECONCILIATION_AMOUNT_MISMATCH');return Object.freeze({...batch,batchHash:canonicalHash(batch),reconciledAmountCents:amountCents})}
export class MemoryImportSimulator{#records=new Map();#batches=new Map();import(batch,manifest){const valid=validateCanonicalBatch(batch,manifest),prior=this.#batches.get(valid.batchId);if(prior){if(prior.batchHash!==valid.batchHash)fail('BATCH_ID_CONFLICT');return Object.freeze({...prior,replayed:true})}const plan=valid.records.map(record=>{const key=`${valid.tenantId}:${valid.domain}:${record.canonicalKey}`,hash=canonicalHash(record.payload),existing=this.#records.get(key);if(existing&&existing.hash!==hash)fail('CANONICAL_KEY_CONFLICT');return{key,hash,payload:record.payload,duplicate:Boolean(existing)}});for(const item of plan)if(!item.duplicate)this.#records.set(item.key,{hash:item.hash,payload:item.payload});const report=Object.freeze({batchId:valid.batchId,batchHash:valid.batchHash,tenantId:valid.tenantId,domain:valid.domain,input:plan.length,amountCents:valid.reconciledAmountCents,inserted:plan.filter(item=>!item.duplicate).length,duplicates:plan.filter(item=>item.duplicate).length,rejected:0,replayed:false,payloadPrinted:false,persisted:false});this.#batches.set(valid.batchId,report);return report}count({tenantId,domain}){return[...this.#records.keys()].filter(key=>key.startsWith(`${tenantId}:${domain}:`)).length}}
export const importDomains=Object.freeze([...DOMAINS]);
