'use client';
import Image from 'next/image';
import { useState } from 'react';
import connectionCyberLogo from '../../../../logo/logosf.png';
type Profile='MEI'|'ME'|'LTDA'; type ModuleKey='inicio'|'cadastros'|'estoque'|'vendas'|'caixa'|'financeiro';
const profiles:Record<Profile,{company:string;subtitle:string;accent:string;enabled:ModuleKey[]}>= {
 MEI:{company:'SYNTHETIC Studio Criativo',subtitle:'Microempreendedor individual',accent:'Perfil essencial',enabled:['inicio','cadastros','vendas','caixa','financeiro']},
 ME:{company:'SYNTHETIC Moda & Cia',subtitle:'Microempresa · varejo',accent:'Perfil varejo',enabled:['inicio','cadastros','estoque','vendas','caixa','financeiro']},
 LTDA:{company:'SYNTHETIC Grupo Comercial',subtitle:'Sociedade limitada · multiunidade',accent:'Perfil avançado',enabled:['inicio','cadastros','estoque','vendas','caixa','financeiro']}};
const modules:{key:ModuleKey;label:string;icon:string}[]=[{key:'inicio',label:'Visão geral',icon:'⌂'},{key:'cadastros',label:'Cadastros',icon:'◇'},{key:'estoque',label:'Estoque',icon:'▦'},{key:'vendas',label:'Vendas e PDV',icon:'▤'},{key:'caixa',label:'Caixa',icon:'⊞'},{key:'financeiro',label:'Financeiro',icon:'◫'}];
const copy:Record<ModuleKey,{title:string;text:string}>={inicio:{title:'Seu negócio, em uma visão simples',text:'Acompanhe o que precisa de atenção e continue o trabalho de onde parou.'},cadastros:{title:'Cadastros organizados',text:'Clientes, fornecedores, produtos e serviços no contexto exclusivo desta empresa.'},estoque:{title:'Estoque sob controle',text:'Saldo, movimentações e reposição com rastreabilidade por estabelecimento.'},vendas:{title:'Venda rápida e segura',text:'Orçamentos, pedidos e PDV com totais consistentes e operação idempotente.'},caixa:{title:'Caixa conferido',text:'Abertura, entradas, saídas e fechamento vinculados ao operador e estabelecimento.'},financeiro:{title:'Financeiro previsível',text:'Recebimentos, pagamentos e vencimentos separados por empresa.'}};
export function DemoDashboard(){const[profile,setProfile]=useState<Profile>('ME'),[active,setActive]=useState<ModuleKey>('inicio'),current=profiles[profile];const choose=(next:Profile)=>{setProfile(next);if(!profiles[next].enabled.includes(active))setActive('inicio')};return <div className="demo-shell">
<header className="demo-topbar"><div className="demo-brand"><Image src={connectionCyberLogo} width={42} height={42} alt="ConnectionCyber"/><span><strong>ConnectionCyber</strong><small>Gestão empresarial</small></span></div><div className="demo-company"><span>Empresa ativa</span><strong>{current.company}</strong><small>{current.subtitle}</small></div><button className="demo-user" type="button" aria-label="Perfil sintético"><span>JS</span><b>Joaquim</b></button></header>
<aside className="demo-sidebar"><div className="demo-context"><span>Ambiente demonstrativo</span><strong>{current.accent}</strong><small>Nenhum dado real</small></div><nav aria-label="Navegação demonstrativa">{modules.map(module=>{const enabled=current.enabled.includes(module.key);return <button key={module.key} type="button" disabled={!enabled} className={active===module.key?'active':''} onClick={()=>setActive(module.key)}><i>{module.icon}</i><span>{module.label}</span>{!enabled?<small>Indisponível</small>:null}</button>})}</nav><div className="demo-help"><span>Precisa de ajuda?</span><strong>Suporte ConnectionCyber</strong><small>Atendimento protegido por consentimento</small></div></aside>
<main className="demo-main"><div className="demo-warning"><strong>DEMONSTRAÇÃO LOCAL</strong><span>Dados totalmente sintéticos · sem conexão com produção</span></div><section className="demo-heading"><div><span className="eyebrow">{copy[active].title}</span><h1>Olá, Joaquim.</h1><p>{copy[active].text}</p></div><div className="profile-switch" aria-label="Selecionar perfil empresarial">{(['MEI','ME','LTDA'] as Profile[]).map(item=><button type="button" className={profile===item?'active':''} key={item} onClick={()=>choose(item)}>{item}</button>)}</div></section>
<section className="demo-kpis" aria-label="Indicadores sintéticos"><article><span>Vendas hoje</span><strong>{profile==='MEI'?'R$ 840':profile==='ME'?'R$ 4.280':'R$ 18.640'}</strong><small className="positive">↑ 12% nesta semana</small></article><article><span>Receber em 7 dias</span><strong>{profile==='LTDA'?'R$ 24.900':'R$ 3.760'}</strong><small>8 títulos previstos</small></article><article><span>Estoque crítico</span><strong>{profile==='MEI'?'—':profile==='ME'?'6 itens':'19 itens'}</strong><small className={profile==='MEI'?'':'attention'}>{profile==='MEI'?'Módulo não contratado':'Revisar reposição'}</small></article><article><span>Caixa atual</span><strong>R$ 1.245</strong><small className="positive">Sessão conferida</small></article></section>
<div className="demo-columns"><section className="demo-panel demo-quick"><div className="panel-title"><div><span className="eyebrow">Acesso rápido</span><h2>O que você quer fazer?</h2></div></div><div className="quick-grid"><button type="button" onClick={()=>setActive('vendas')}><b>＋</b><span><strong>Nova venda</strong><small>Abrir PDV</small></span></button><button type="button" onClick={()=>setActive('cadastros')}><b>◇</b><span><strong>Novo cadastro</strong><small>Cliente ou produto</small></span></button><button type="button" onClick={()=>setActive('financeiro')}><b>↗</b><span><strong>Lançar título</strong><small>Receber ou pagar</small></span></button><button type="button" onClick={()=>setActive('caixa')}><b>✓</b><span><strong>Conferir caixa</strong><small>Movimentos do dia</small></span></button></div></section><section className="demo-panel"><div className="panel-title"><div><span className="eyebrow">Próximos passos</span><h2>Atenção necessária</h2></div><button type="button">Ver tudo</button></div><ul className="task-list"><li><i className="orange">!</i><span><strong>6 produtos abaixo do mínimo</strong><small>Estoque · hoje</small></span><b>Repor</b></li><li><i className="blue">$</i><span><strong>3 recebimentos vencem amanhã</strong><small>Financeiro · R$ 1.890</small></span><b>Revisar</b></li><li><i className="green">✓</i><span><strong>Caixa de ontem conferido</strong><small>Sem divergências</small></span><b>Concluído</b></li></ul></section></div></main>
<footer className="demo-footer"><span>Tecnologia que traz conhecimento e gestão</span><span>Perfil {profile} · isolamento por empresa</span></footer></div>}
