'use client';
import { useMemo, useState } from 'react';
import type { DemoProduct } from '../domain/demo-store';

type Movement={id:string;product:string;kind:'Entrada'|'Saída';quantity:number;balance:number};
export function DemoInventory({products,onAdjust,onClose}:{products:DemoProduct[];onAdjust:(id:string,delta:number)=>void;onClose:()=>void}){
 const[productId,setProductId]=useState(products[0]?.id??''),[kind,setKind]=useState<'Entrada'|'Saída'>('Entrada'),[quantity,setQuantity]=useState('1'),[message,setMessage]=useState(''),[movements,setMovements]=useState<Movement[]>([]),[query,setQuery]=useState('');
 const selected=products.find(item=>item.id===productId),filtered=useMemo(()=>products.filter(item=>(item.name+item.code).toLowerCase().includes(query.toLowerCase())),[products,query]);
 const apply=()=>{const amount=Number(quantity);if(!selected||!Number.isInteger(amount)||amount<=0){setMessage('Informe um produto e uma quantidade inteira positiva.');return}const delta=kind==='Entrada'?amount:-amount;if(selected.stock+delta<0){setMessage(`Saída bloqueada: saldo atual de ${selected.stock} unidade(s).`);return}onAdjust(selected.id,delta);const balance=selected.stock+delta;setMovements(current=>[{id:`MOV-${String(current.length+1).padStart(3,'0')}`,product:selected.name,kind,quantity:amount,balance},...current]);setMessage(`${kind} sintética aplicada. Novo saldo: ${balance}.`)};
 return <section className="inventory-screen"><header className="registration-heading"><div><button type="button" className="pos-back" onClick={onClose}>← Voltar ao painel</button><span className="eyebrow">Estoque · memória local</span><h1>Movimentação de estoque</h1><p>Entradas e saídas alteram imediatamente a disponibilidade no PDV.</p></div><div className="registration-session"><strong>Operação sintética</strong><small>Nenhuma movimentação será persistida.</small></div></header>{message?<p className="registration-message" role="status">{message}</p>:null}<div className="inventory-layout"><section className="registration-form"><span className="eyebrow">Novo movimento</span><label>Produto<select value={productId} onChange={event=>setProductId(event.target.value)}>{products.map(item=><option value={item.id} key={item.id}>{item.name} · saldo {item.stock}</option>)}</select></label><div className="registration-row"><label>Operação<select value={kind} onChange={event=>setKind(event.target.value as 'Entrada'|'Saída')}><option>Entrada</option><option>Saída</option></select></label><label>Quantidade<input type="number" min="1" step="1" value={quantity} onChange={event=>setQuantity(event.target.value)}/></label></div><button type="button" className="button primary" onClick={apply}>Aplicar movimento</button><small>Saídas acima do saldo são bloqueadas.</small></section><section className="registration-list"><label className="pos-search"><span>⌕</span><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar produto ou código"/></label><h2>{filtered.length} produtos</h2>{filtered.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.code}</small></div><b className={item.stock<=5?'stock-low':''}>{item.stock} un.</b></article>)}</section></div>{movements.length?<section className="inventory-ledger"><span className="eyebrow">Movimentos desta sessão</span>{movements.map(item=><article key={item.id}><strong>{item.id}</strong><span>{item.product}</span><b>{item.kind} · {item.quantity}</b><small>Saldo {item.balance}</small></article>)}</section>:null}</section>;
}
