'use client';
import Image from 'next/image';
import { useState } from 'react';
import connectionCyberLogo from '../../../../logo/logosf.png';
import { DemoPos } from './DemoPos';
import { DemoRegistrations } from './DemoRegistrations';
import { DemoInventory } from './DemoInventory';
import { DemoCash } from './DemoCash';
import { DemoFinance, initialDemoTitles } from './DemoFinance';
import { initialDemoCustomers, initialDemoProducts, type DemoCashMovement, type DemoFinancialTitle, type DemoPayment } from '../domain/demo-store';
type Profile='MEI'|'ME'|'LTDA'; type ModuleKey='inicio'|'cadastros'|'estoque'|'vendas'|'caixa'|'financeiro';
const profiles:Record<Profile,{company:string;subtitle:string;accent:string;enabled:ModuleKey[]}>= {MEI:{company:'SYNTHETIC Studio Criativo',subtitle:'Microempreendedor individual',accent:'Perfil essencial',enabled:['inicio','cadastros','vendas','caixa','financeiro']},ME:{company:'SYNTHETIC Moda & Cia',subtitle:'Microempresa · varejo',accent:'Perfil varejo',enabled:['inicio','cadastros','estoque','vendas','caixa','financeiro']},LTDA:{company:'SYNTHETIC Grupo Comercial',subtitle:'Sociedade limitada · multiunidade',accent:'Perfil avançado',enabled:['inicio','cadastros','estoque','vendas','caixa','financeiro']}};
const modules:{key:ModuleKey;label:string;icon:string}[]=[{key:'inicio',label:'Visão geral',icon:'⌂'},{key:'cadastros',label:'Cadastros',icon:'◇'},{key:'estoque',label:'Estoque',icon:'▦'},{key:'vendas',label:'Vendas e PDV',icon:'▤'},{key:'caixa',label:'Caixa',icon:'⊞'},{key:'financeiro',label:'Financeiro',icon:'◫'}];
const copy:Record<ModuleKey,{title:string;text:string}>={inicio:{title:'Seu negócio, em uma visão simples',text:'Acompanhe o que precisa de atenção e continue o trabalho de onde parou.'},cadastros:{title:'Cadastros organizados',text:'Clientes, fornecedores, produtos e serviços no contexto exclusivo desta empresa.'},estoque:{title:'Estoque sob controle',text:'Saldo, movimentações e reposição com rastreabilidade por estabelecimento.'},vendas:{title:'Venda rápida e segura',text:'Orçamentos, pedidos e PDV com totais consistentes e operação idempotente.'},caixa:{title:'Caixa conferido',text:'Abertura, entradas, saídas e fechamento vinculados ao operador e estabelecimento.'},financeiro:{title:'Financeiro previsível',text:'Recebimentos, pagamentos e vencimentos separados por empresa.'}};
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function DemoDashboard(){const[profile,setProfile]=useState<Profile>('ME'),[active,setActive]=useState<ModuleKey>('inicio'),[posOpen,setPosOpen]=useState(false),[registrationOpen,setRegistrationOpen]=useState(false),[inventoryOpen,setInventoryOpen]=useState(false),[cashScreenOpen,setCashScreenOpen]=useState(false),[financeOpen,setFinanceOpen]=useState(false),[cashOpen,setCashOpen]=useState(false),[cashMovements,setCashMovements]=useState<DemoCashMovement[]>([]),[financialTitles,setFinancialTitles]=useState<DemoFinancialTitle[]>(initialDemoTitles),[products,setProducts]=useState(initialDemoProducts),[customers,setCustomers]=useState(initialDemoCustomers),current=profiles[profile],cashBalance=cashMovements.reduce((sum,item)=>item.kind==='Saída'||item.kind==='Fechamento'?sum-item.amount:sum+item.amount,0),sessionSales=cashMovements.filter(item=>item.kind==='Venda').reduce((sum,item)=>sum+item.amount,0),criticalStock=products.filter(item=>item.stock<=5).length,openReceivable=financialTitles.filter(item=>item.kind==='Receber'&&item.status==='Aberto').reduce((sum,item)=>sum+item.amount,0),openPayable=financialTitles.filter(item=>item.kind==='Pagar'&&item.status==='Aberto').reduce((sum,item)=>sum+item.amount,0);const choose=(next:Profile)=>{setProfile(next);if(!profiles[next].enabled.includes(active))setActive('inicio')};const closeFlows=()=>{setPosOpen(false);setRegistrationOpen(false);setInventoryOpen(false);setCashScreenOpen(false);setFinanceOpen(false)},openPos=()=>{closeFlows();setPosOpen(true)},openRegistrations=()=>{closeFlows();setRegistrationOpen(true);setActive('cadastros')},openInventory=()=>{closeFlows();setInventoryOpen(true);setActive('estoque')},openCash=()=>{closeFlows();setCashScreenOpen(true);setActive('caixa')},openFinance=()=>{closeFlows();setFinanceOpen(true);setActive('financeiro')},addCashMovement=(movement:Omit<DemoCashMovement,'id'>)=>setCashMovements(current=>[...current,{...movement,id:`CASH-${String(current.length+1).padStart(3,'0')}`}]),recordSale=(amount:number,payment:DemoPayment)=>addCashMovement({kind:'Venda',amount,label:'Venda sintética do PDV',payment});return <div className="demo-shell">
<header className="demo-topbar"><div className="demo-brand"><Image src={connectionCyberLogo} width={42} height={42} alt="ConnectionCyber"/><span><strong>ConnectionCyber</strong><small>Gestão empresarial</small></span></div><div className="demo-company"><span>Empresa ativa</span><strong>{current.company}</strong><small>{current.subtitle}</small></div><button className="demo-user" type="button" aria-label="Perfil sintético"><span>JS</span><b>Joaquim</b></button></header>
<aside className="demo-sidebar"><div className="demo-context"><span>Ambiente demonstrativo</span><strong>{current.accent}</strong><small>Nenhum dado real</small></div><nav aria-label="Navegação demonstrativa">{modules.map(module=>{const enabled=current.enabled.includes(module.key);return <button key={module.key} type="button" disabled={!enabled} className={active===module.key?'active':''} onClick={()=>{setActive(module.key);if(module.key==='vendas')openPos();else if(module.key==='cadastros')openRegistrations();else if(module.key==='estoque')openInventory();else if(module.key==='caixa')openCash();else if(module.key==='financeiro')openFinance();else closeFlows()}}><i>{module.icon}</i><span>{module.label}</span>{!enabled?<small>Indisponível</small>:null}</button>})}</nav><div className="demo-help"><span>Precisa de ajuda?</span><strong>Suporte ConnectionCyber</strong><small>Atendimento protegido por consentimento</small></div></aside>
<main className="demo-main"><div className="demo-warning"><strong>DEMONSTRAÇÃO LOCAL</strong><span>Dados totalmente sintéticos · sem conexão com produção</span></div>{posOpen?<DemoPos products={products} customers={customers} cashOpen={cashOpen} onSaleComplete={recordSale} onClose={()=>setPosOpen(false)}/>:registrationOpen?<DemoRegistrations products={products} customers={customers} onAddProduct={product=>setProducts(current=>[...current,product])} onAddCustomer={customer=>setCustomers(current=>[...current,customer])} onClose={()=>setRegistrationOpen(false)}/>:inventoryOpen?<DemoInventory products={products} onAdjust={(id,delta)=>setProducts(current=>current.map(product=>product.id===id?{...product,stock:product.stock+delta}:product))} onClose={()=>setInventoryOpen(false)}/>:cashScreenOpen?<DemoCash open={cashOpen} movements={cashMovements} onOpen={amount=>{setCashOpen(true);addCashMovement({kind:'Abertura',amount,label:'Fundo de abertura sintético'})}} onMovement={addCashMovement} onCloseCash={amount=>{addCashMovement({kind:'Fechamento',amount,label:'Fechamento conferido'});setCashOpen(false)}} onBack={()=>setCashScreenOpen(false)}/>:financeOpen?<DemoFinance titles={financialTitles} onTitlesChange={setFinancialTitles} cashOpen={cashOpen} cashBalance={cashBalance} onCashMovement={addCashMovement} onBack={()=>setFinanceOpen(false)}/>:<><section className="demo-heading"><div><span className="eyebrow">{copy[active].title}</span><h1>Olá, Joaquim.</h1><p>{copy[active].text}</p></div><div className="profile-switch" aria-label="Selecionar perfil empresarial">{(['MEI','ME','LTDA'] as Profile[]).map(item=><button type="button" className={profile===item?'active':''} key={item} onClick={()=>choose(item)}>{item}</button>)}</div></section>
<section className="demo-kpis" aria-label="Indicadores sintéticos"><article><span>Vendas da sessão</span><strong>{money(sessionSales)}</strong><small className="positive">{cashMovements.filter(item=>item.kind==='Venda').length} vendas concluídas</small></article><article><span>A receber em aberto</span><strong>{money(openReceivable)}</strong><small>A pagar: {money(openPayable)}</small></article><article><span>Estoque crítico</span><strong>{profile==='MEI'?'—':`${criticalStock} itens`}</strong><small className={profile==='MEI'?'':'attention'}>{profile==='MEI'?'Módulo não contratado':'Saldo igual ou inferior a 5'}</small></article><article><span>Caixa da sessão</span><strong>{money(cashBalance)}</strong><small className={cashOpen?'positive':'attention'}>{cashOpen?'Caixa aberto':'Caixa fechado'}</small></article></section>
<div className="demo-columns"><section className="demo-panel demo-quick"><div className="panel-title"><div><span className="eyebrow">Acesso rápido</span><h2>O que você quer fazer?</h2></div></div><div className="quick-grid"><button type="button" onClick={openPos}><b>＋</b><span><strong>Nova venda</strong><small>Abrir PDV</small></span></button><button type="button" onClick={openRegistrations}><b>◇</b><span><strong>Novo cadastro</strong><small>Cliente ou produto</small></span></button><button type="button" onClick={openFinance}><b>↗</b><span><strong>Lançar título</strong><small>Receber ou pagar</small></span></button><button type="button" onClick={openCash}><b>✓</b><span><strong>Conferir caixa</strong><small>Movimentos do dia</small></span></button></div></section><section className="demo-panel"><div className="panel-title"><div><span className="eyebrow">Estado da sessão</span><h2>Operação integrada</h2></div></div><ul className="task-list"><li><i className="orange">!</i><span><strong>{criticalStock} produtos com estoque crítico</strong><small>Estoque · saldo até 5 unidades</small></span><button type="button" onClick={openInventory}>Revisar</button></li><li><i className="blue">$</i><span><strong>{money(openReceivable)} a receber</strong><small>Financeiro · {financialTitles.filter(item=>item.status==='Aberto').length} títulos abertos</small></span><button type="button" onClick={openFinance}>Revisar</button></li><li><i className="green">✓</i><span><strong>{cashOpen?'Caixa aberto':'Caixa fechado'}</strong><small>Saldo {money(cashBalance)}</small></span><button type="button" onClick={openCash}>Conferir</button></li></ul></section></div></>}</main>
<footer className="demo-footer"><span>Tecnologia que traz conhecimento e gestão</span><span>Perfil {profile} · isolamento por empresa</span></footer></div>}
