'use client';
import { useMemo, useState } from 'react';
import type { DemoCashMovement, DemoFinancialTitle } from '../domain/demo-store';
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const initialTitles:DemoFinancialTitle[]=[{id:'FIN-001',kind:'Receber',description:'Venda a prazo sintética',amount:480,due:'2026-09-02',status:'Aberto'},{id:'FIN-002',kind:'Pagar',description:'Fornecedor sintético',amount:210,due:'2026-09-04',status:'Aberto'}];
export function DemoFinance({cashOpen,cashBalance,onCashMovement,onBack}:{cashOpen:boolean;cashBalance:number;onCashMovement:(movement:Omit<DemoCashMovement,'id'>)=>void;onBack:()=>void}){
 const[titles,setTitles]=useState(initialTitles),[kind,setKind]=useState<'Receber'|'Pagar'>('Receber'),[description,setDescription]=useState('Título sintético'),[amount,setAmount]=useState('100'),[due,setDue]=useState('2026-09-05'),[message,setMessage]=useState(''),[filter,setFilter]=useState<'Todos'|'Receber'|'Pagar'>('Todos');
 const openTitles=titles.filter(item=>item.status==='Aberto'),receivable=useMemo(()=>openTitles.filter(item=>item.kind==='Receber').reduce((sum,item)=>sum+item.amount,0),[openTitles]),payable=useMemo(()=>openTitles.filter(item=>item.kind==='Pagar').reduce((sum,item)=>sum+item.amount,0),[openTitles]),visible=titles.filter(item=>filter==='Todos'||item.kind===filter);
 const createTitle=()=>{const value=Number(amount);if(!description.trim()||value<=0||!due){setMessage('Informe descrição, valor positivo e vencimento.');return}const title:DemoFinancialTitle={id:`FIN-${String(titles.length+1).padStart(3,'0')}`,kind,description:description.trim(),amount:value,due,status:'Aberto'};setTitles(current=>[title,...current]);setMessage(`${kind} de ${money(value)} criado somente nesta sessão.`)};
 const settle=(title:DemoFinancialTitle)=>{if(title.status==='Baixado'){setMessage('Título já baixado.');return}if(!cashOpen){setMessage('Abra o caixa antes de realizar a baixa financeira.');return}if(title.kind==='Pagar'&&title.amount>cashBalance){setMessage(`Pagamento bloqueado: caixa disponível ${money(cashBalance)}.`);return}setTitles(current=>current.map(item=>item.id===title.id?{...item,status:'Baixado'}:item));onCashMovement({kind:title.kind==='Receber'?'Entrada':'Saída',amount:title.amount,label:`Baixa ${title.id} · ${title.description}`});setMessage(`${title.id} baixado e refletido no caixa.`)};
 return <section className="finance-screen"><header className="registration-heading"><div><button type="button" className="pos-back" onClick={onBack}>← Voltar ao painel</button><span className="eyebrow">Financeiro · memória local</span><h1>Contas a pagar e receber</h1><p>Baixas financeiras atualizam o caixa aberto desta sessão.</p></div><div className={`cash-state ${cashOpen?'open':'closed'}`}><span>{cashOpen?'CAIXA DISPONÍVEL':'CAIXA FECHADO'}</span><strong>{money(cashBalance)}</strong><small>Baixas protegidas por saldo</small></div></header>{message?<p className="registration-message" role="status">{message}</p>:null}<section className="finance-kpis"><article><span>A receber</span><strong>{money(receivable)}</strong><small>{openTitles.filter(item=>item.kind==='Receber').length} títulos abertos</small></article><article><span>A pagar</span><strong>{money(payable)}</strong><small>{openTitles.filter(item=>item.kind==='Pagar').length} títulos abertos</small></article><article><span>Saldo projetado</span><strong>{money(receivable-payable)}</strong><small>Somente títulos sintéticos</small></article></section><div className="finance-layout"><section className="registration-form"><span className="eyebrow">Novo título</span><label>Tipo<select value={kind} onChange={event=>setKind(event.target.value as 'Receber'|'Pagar')}><option>Receber</option><option>Pagar</option></select></label><label>Descrição<input value={description} onChange={event=>setDescription(event.target.value)}/></label><div className="registration-row"><label>Valor<input type="number" min="0.01" step="0.01" value={amount} onChange={event=>setAmount(event.target.value)}/></label><label>Vencimento<input type="date" value={due} onChange={event=>setDue(event.target.value)}/></label></div><button type="button" className="button primary" onClick={createTitle}>Criar título</button></section><section className="finance-titles"><div className="finance-filter">{(['Todos','Receber','Pagar'] as const).map(item=><button type="button" className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div>{visible.map(title=><article key={title.id} className={title.status==='Baixado'?'settled':''}><span className={title.kind==='Receber'?'cash-in':'cash-out'}>{title.kind==='Receber'?'↓':'↑'}</span><div><strong>{title.description}</strong><small>{title.id} · vence {new Date(`${title.due}T12:00:00`).toLocaleDateString('pt-BR')}</small></div><b>{money(title.amount)}</b><button type="button" disabled={title.status==='Baixado'} onClick={()=>settle(title)}>{title.status==='Baixado'?'Baixado':'Dar baixa'}</button></article>)}</section></div></section>;
}
