'use client';
import { useMemo, useState } from 'react';
import type { DemoCashMovement } from '../domain/demo-store';
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
export function DemoCash({open,movements,onOpen,onMovement,onCloseCash,onBack}:{open:boolean;movements:DemoCashMovement[];onOpen:(amount:number)=>void;onMovement:(movement:Omit<DemoCashMovement,'id'>)=>void;onCloseCash:(declared:number)=>void;onBack:()=>void}){
 const[value,setValue]=useState('100'),[kind,setKind]=useState<'Entrada'|'Saída'>('Entrada'),[label,setLabel]=useState('Reforço sintético'),[declared,setDeclared]=useState(''),[message,setMessage]=useState('');
 const balance=useMemo(()=>movements.reduce((sum,item)=>item.kind==='Saída'||item.kind==='Fechamento'?sum-item.amount:sum+item.amount,0),[movements]);
 const openSession=()=>{const amount=Number(value);if(open){setMessage('Caixa já está aberto.');return}if(amount<0){setMessage('O valor de abertura não pode ser negativo.');return}onOpen(amount);setMessage(`Caixa aberto com ${money(amount)}.`)};
 const addMovement=()=>{const amount=Number(value);if(!open){setMessage('Abra o caixa antes de movimentar.');return}if(amount<=0||!label.trim()){setMessage('Informe descrição e valor positivo.');return}if(kind==='Saída'&&amount>balance){setMessage(`Saída bloqueada: saldo disponível ${money(balance)}.`);return}onMovement({kind,amount,label:label.trim()});setMessage(`${kind} sintética de ${money(amount)} aplicada.`)};
 const closeSession=()=>{const amount=Number(declared);if(!open){setMessage('O caixa já está fechado.');return}if(amount<0||declared===''){setMessage('Informe o saldo contado para fechar.');return}const difference=amount-balance;if(Math.abs(difference)>.009){setMessage(`Fechamento bloqueado: diferença de ${money(difference)}.`);return}onCloseCash(amount);setMessage('Caixa fechado e conferido sem divergência.')};
 return <section className="cash-screen"><header className="registration-heading"><div><button type="button" className="pos-back" onClick={onBack}>← Voltar ao painel</button><span className="eyebrow">Caixa · memória local</span><h1>Controle de caixa</h1><p>Vendas do PDV entram automaticamente nesta sessão.</p></div><div className={`cash-state ${open?'open':'closed'}`}><span>{open?'CAIXA ABERTO':'CAIXA FECHADO'}</span><strong>{money(balance)}</strong><small>SYNTHETIC-01 · operador Joaquim</small></div></header>{message?<p className="registration-message" role="status">{message}</p>:null}<div className="cash-actions"><section className="registration-form"><span className="eyebrow">{open?'Movimento avulso':'Abertura'}</span>{open?<><label>Operação<select value={kind} onChange={event=>setKind(event.target.value as 'Entrada'|'Saída')}><option>Entrada</option><option>Saída</option></select></label><label>Descrição<input value={label} onChange={event=>setLabel(event.target.value)}/></label></>:null}<label>Valor<input type="number" min="0" step="0.01" value={value} onChange={event=>setValue(event.target.value)}/></label><button type="button" className="button primary" onClick={open?addMovement:openSession}>{open?'Aplicar movimento':'Abrir caixa'}</button></section><section className="registration-form"><span className="eyebrow">Fechamento conferido</span><label>Saldo contado<input type="number" min="0" step="0.01" value={declared} onChange={event=>setDeclared(event.target.value)} placeholder={balance.toFixed(2)}/></label><button type="button" className="button secondary" disabled={!open} onClick={closeSession}>Fechar caixa</button><small>Diferenças bloqueiam o fechamento nesta demonstração.</small></section></div><section className="cash-ledger"><div><span className="eyebrow">Movimentos da sessão</span><h2>{movements.length} lançamentos</h2></div>{movements.length?movements.map(item=><article key={item.id}><span className={item.kind==='Saída'||item.kind==='Fechamento'?'cash-out':'cash-in'}>{item.kind==='Saída'||item.kind==='Fechamento'?'−':'+'}</span><div><strong>{item.label}</strong><small>{item.kind}{item.payment?` · ${item.payment}`:''}</small></div><b>{money(item.amount)}</b></article>):<p className="cash-empty">Abra o caixa para iniciar a sessão.</p>}</section></section>;
}
