'use client';
import { FormEvent, useState } from 'react';
import type { DemoCustomer, DemoProduct } from '../domain/demo-store';

type Props={customers:DemoCustomer[];products:DemoProduct[];onAddCustomer:(customer:DemoCustomer)=>void;onAddProduct:(product:DemoProduct)=>void;onClose:()=>void};
const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function DemoRegistrations({customers,products,onAddCustomer,onAddProduct,onClose}:Props){
  const[tab,setTab]=useState<'cliente'|'produto'>('cliente');
  const[message,setMessage]=useState('');
  const[customerName,setCustomerName]=useState('');
  const[customerEmail,setCustomerEmail]=useState('');
  const[customerKind,setCustomerKind]=useState<DemoCustomer['kind']>('Pessoa');
  const[productName,setProductName]=useState('');
  const[productPrice,setProductPrice]=useState('');
  const[productStock,setProductStock]=useState('');
  const addCustomer=(event:FormEvent)=>{event.preventDefault();const name=customerName.trim(),email=customerEmail.trim();if(!name||!email.endsWith('.invalid')){setMessage('Use um nome e um e-mail sintético terminado em .invalid.');return}const next:DemoCustomer={id:`synthetic-customer-${String(customers.length+1).padStart(3,'0')}`,name,email,kind:customerKind};onAddCustomer(next);setCustomerName('');setCustomerEmail('');setMessage(`${name} disponível no PDV durante esta sessão.`)};
  const addProduct=(event:FormEvent)=>{event.preventDefault();const name=productName.trim(),price=Number(productPrice),stock=Number(productStock);if(!name||price<=0||!Number.isInteger(stock)||stock<0){setMessage('Informe nome, preço positivo e estoque inteiro não negativo.');return}const serial=String(products.length+1).padStart(3,'0');const next:DemoProduct={id:`synthetic-${serial}`,code:`SYN-${serial}`,name,price,stock};onAddProduct(next);setProductName('');setProductPrice('');setProductStock('');setMessage(`${name} disponível no catálogo do PDV durante esta sessão.`)};
  return <section className="registration-screen"><header className="registration-heading"><div><button type="button" className="pos-back" onClick={onClose}>← Voltar ao painel</button><span className="eyebrow">Cadastros · memória local</span><h1>Cliente e produto</h1><p>Cadastre dados sintéticos para usar imediatamente no PDV.</p></div><div className="registration-session"><strong>Somente nesta sessão</strong><small>Ao recarregar a página, os novos dados serão descartados.</small></div></header>
  <div className="registration-tabs" role="tablist"><button type="button" className={tab==='cliente'?'active':''} onClick={()=>{setTab('cliente');setMessage('')}}>Novo cliente</button><button type="button" className={tab==='produto'?'active':''} onClick={()=>{setTab('produto');setMessage('')}}>Novo produto</button></div>
  {message?<p className="registration-message" role="status">{message}</p>:null}
  <div className="registration-layout">{tab==='cliente'?<form className="registration-form" onSubmit={addCustomer}><div><span className="eyebrow">Cliente sintético</span><h2>Dados básicos</h2></div><label>Nome sintético<input required value={customerName} onChange={event=>setCustomerName(event.target.value)} placeholder="Ex.: Cliente Teste Sintético"/></label><label>E-mail reservado para testes<input required type="email" value={customerEmail} onChange={event=>setCustomerEmail(event.target.value)} placeholder="cliente@example.invalid"/></label><label>Tipo<select value={customerKind} onChange={event=>setCustomerKind(event.target.value as DemoCustomer['kind'])}><option>Pessoa</option><option>Empresa</option></select></label><button className="button primary" type="submit">Cadastrar cliente</button><small>CPF, CNPJ e qualquer identidade real estão fora desta demonstração.</small></form>:<form className="registration-form" onSubmit={addProduct}><div><span className="eyebrow">Produto sintético</span><h2>Dados comerciais</h2></div><label>Descrição<input required value={productName} onChange={event=>setProductName(event.target.value)} placeholder="Ex.: Mochila Sintética"/></label><div className="registration-row"><label>Preço<input required type="number" min="0.01" step="0.01" value={productPrice} onChange={event=>setProductPrice(event.target.value)} placeholder="149,90"/></label><label>Estoque<input required type="number" min="0" step="1" value={productStock} onChange={event=>setProductStock(event.target.value)} placeholder="7"/></label></div><button className="button primary" type="submit">Cadastrar produto</button><small>O código SYN-{String(products.length+1).padStart(3,'0')} será gerado automaticamente.</small></form>}
  <aside className="registration-list"><span className="eyebrow">Disponíveis no PDV</span><h2>{tab==='cliente'?`${customers.length} clientes`:`${products.length} produtos`}</h2>{tab==='cliente'?customers.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.kind} · {item.email}</small></div><b>Ativo</b></article>):products.map(item=><article key={item.id}><div><strong>{item.name}</strong><small>{item.code} · {item.stock} em estoque</small></div><b>{money(item.price)}</b></article>)}</aside></div></section>;
}
