import test from'node:test';import assert from'node:assert/strict';import{AUTHORITY_FIELDS,COMMAND_BOUNDARIES,CONTRACT_VERSION,PUBLIC_ERRORS,READ_MODELS,SECRET_FIELDS,THREAT_MODEL,UX_STATES,toPublicError,transitionUx,validateBrowserPayload,validateVisualPersistenceContract}from'../src/index.mjs';
test('versão canônica M18 é fixa',()=>assert.equal(CONTRACT_VERSION,'M18-VISUAL-1.0'));
test('contrato cobre sete comandos',()=>assert.equal(Object.keys(COMMAND_BOUNDARIES).length,7));
test('cada comando usa RPC v1',()=>assert.equal(Object.values(COMMAND_BOUNDARIES).every(x=>x.rpc.endsWith('_v1')),true));
test('cada comando mapeia tela',()=>assert.equal(Object.values(COMMAND_BOUNDARIES).every(x=>x.screen.startsWith('/')),true));
test('cada comando exige releitura',()=>assert.equal(Object.values(COMMAND_BOUNDARIES).every(x=>x.refresh.length>0),true));
test('todas as releituras existem',()=>assert.equal(Object.values(COMMAND_BOUNDARIES).flatMap(x=>x.refresh).every(x=>READ_MODELS[x]),true));
test('read models resolvem tenant no servidor',()=>assert.equal(Object.values(READ_MODELS).every(x=>x.tenantFilter==='server-resolved'),true));
test('read models possuem vazio explícito',()=>assert.equal(Object.values(READ_MODELS).every(x=>x.empty.length>0),true));
test('dashboard é releitura server-side',()=>assert.equal(READ_MODELS['dashboard-summary'].source,'server-aggregate'));
test('venda relê estoque caixa e financeiro',()=>assert.deepEqual(COMMAND_BOUNDARIES['sale.complete'].refresh,['sales','stock-balance','open-cash-sessions','financial-summary']));
test('tenant do navegador é recusado',()=>assert.throws(()=>validateBrowserPayload({tenantId:'x'}),/FORBIDDEN_BROWSER_FIELD/));
test('autoridade aninhada é recusada',()=>assert.throws(()=>validateBrowserPayload({meta:{grandTotal:1}}),/FORBIDDEN_BROWSER_FIELD/));
test('segredo aninhado é recusado',()=>assert.throws(()=>validateBrowserPayload({meta:{token:'x'}}),/FORBIDDEN_BROWSER_FIELD/));
test('campos normais são aceitos',()=>assert.equal(validateBrowserPayload({name:'SYNTHETIC',lines:[{quantity:1}]}),true));
test('papel comercial de cadastro é aceito',()=>assert.equal(validateBrowserPayload({role:'customer'}),true));
test('array raiz é recusado',()=>assert.throws(()=>validateBrowserPayload([]),/INVALID_INPUT/));
test('payload maior que 64 KiB é recusado',()=>assert.throws(()=>validateBrowserPayload({name:'x'.repeat(65537)}),/PAYLOAD_TOO_LARGE/));
test('listas proibidas não são vazias',()=>assert.equal(AUTHORITY_FIELDS.length>10&&SECRET_FIELDS.length>10,true));
test('submissão exige validação',()=>assert.equal(transitionUx('validating','submitting'),'submitting'));
test('sucesso exige releitura',()=>assert.throws(()=>transitionUx('submitting','succeeded'),/INVALID_UX_TRANSITION/));
test('submitting não é reentrante',()=>assert.throws(()=>transitionUx('submitting','submitting'),/INVALID_UX_TRANSITION/));
test('releitura pode concluir sucesso',()=>assert.equal(transitionUx('revalidating','succeeded'),'succeeded'));
test('falha volta por ação explícita',()=>assert.equal(transitionUx('failed','idle'),'idle'));
test('estados UX cobrem bloqueio',()=>assert.equal(UX_STATES.includes('blocked'),true));
test('erro conhecido vira mensagem segura',()=>assert.equal(toPublicError('ACCESS_DENIED','SQL').message,PUBLIC_ERRORS.ACCESS_DENIED));
test('erro desconhecido vira falha interna',()=>assert.equal(toPublicError('42P01','relation secret').code,'INTERNAL_FAILURE'));
test('erro nunca ativa retry automático',()=>assert.equal(toPublicError('TEMPORARY_FAILURE').retryWriteAutomatically,false));
test('detalhe inseguro não é exposto',()=>assert.equal(toPublicError('INTERNAL_FAILURE','select * from secret').detailExposed,false));
test('modelo contém dez ameaças',()=>assert.equal(THREAT_MODEL.length,10));
test('ameaças têm controle e teste',()=>assert.equal(THREAT_MODEL.every(x=>x.control&&x.test),true));
test('contrato integral é válido',()=>assert.deepEqual(validateVisualPersistenceContract(),{valid:true,findings:[],version:'M18-VISUAL-1.0',commands:7,readModels:11,threats:10,remoteAccessed:false,productionAccessed:false}));
