import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const root = new URL('../../../', import.meta.url);
const migration = await readFile(new URL('supabase/migrations/0049_m23_g3_academy_auto_activation.sql', root), 'utf8');
const preflight = await readFile(new URL('supabase/preflight/0049_m23_g3_academy_auto_activation_preflight.sql', root), 'utf8');
const rollback = await readFile(new URL('supabase/rollback/0049_m23_g3_academy_auto_activation.rollback.sql', root), 'utf8');
const structural = await readFile(new URL('supabase/tests/0049_m23_g3_academy_auto_activation.test.sql', root), 'utf8');
const adversarial = await readFile(new URL('supabase/tests/0049_m23_g3_academy_auto_activation.adversarial.test.sql', root), 'utf8');
const adversarial0048 = await readFile(new URL('supabase/tests/0048_m23_g2_academy_global_catalog.adversarial.test.sql', root), 'utf8');
const builder = await readFile(new URL('supabase/validation/build-0049-transaction.mjs', root), 'utf8');
const runner = await readFile(new URL('supabase/validation/run-0049-remote.ps1', root), 'utf8');
const post = await readFile(new URL('supabase/verification/m23_g3_post_apply.sql', root), 'utf8');

test('migration e transacional',()=>{assert.match(migration,/^--[\s\S]*begin;/i);assert.match(migration,/commit;\s*$/i)});
test('sincronia exige a capacidade nas duas branches do desired',()=>{assert.match(migration,/create or replace function public\.academy_sync_links\(p_course uuid default null\)/);const hits=migration.match(/where erp_security\.academy_capability\(t\.id\)/g)??[];assert.equal(hits.length,2);assert.doesNotMatch(migration,/security invoker/)});
test('gatilhos de capacidade cobrem capabilities e exceptions com filtro de chave',()=>{assert.match(migration,/create or replace function public\.academy_sync_capability_trg\(\)/);assert.match(migration,/case tg_op when 'DELETE' then old\.capability_key else new\.capability_key end/);assert.match(migration,/if v_key='academy\.courses' then/);assert.match(migration,/create trigger trg_academy_capabilities_sync/);assert.match(migration,/create trigger trg_academy_capability_exceptions_sync/);assert.match(migration,/after insert or update or delete on public\.erp_tenant_capabilities/);assert.match(migration,/after insert or update or delete on public\.erp_tenant_capability_exceptions/)});
test('grants da sincronia e do gatilho ficam travados',()=>{assert.match(migration,/revoke all on function public\.academy_sync_links\(uuid\) from public,anon/);assert.match(migration,/grant execute on function public\.academy_sync_links\(uuid\) to authenticated,service_role/);assert.match(migration,/revoke all on function public\.academy_sync_capability_trg\(\) from public,anon/);assert.match(migration,/grant execute on function public\.academy_sync_capability_trg\(\) to authenticated,service_role/)});
test('preflight e somente leitura e observa ausencia',()=>{assert.match(preflight,/M23_G3_PREFLIGHT_OK/);assert.match(preflight,/migration 0049 ja aplicada/);assert.match(preflight,/sincronia ja filtra capacidade/);assert.match(preflight,/gatilhos de capacidade ja existem/);assert.doesNotMatch(preflight,/insert into|update |delete from/i)});
test('rollback desliga os gatilhos e restaura a sincronia da 0048 sem o corte',()=>{assert.match(rollback,/drop trigger if exists trg_academy_capabilities_sync/);assert.match(rollback,/drop trigger if exists trg_academy_capability_exceptions_sync/);assert.match(rollback,/drop function if exists public\.academy_sync_capability_trg\(\)/);assert.match(rollback,/create or replace function public\.academy_sync_links/);assert.doesNotMatch(rollback,/academy_capability\(t\.id\)/);assert.doesNotMatch(rollback,/drop table/i)});
test('builder e runner apontam para o plano 12+24=36',()=>{assert.match(builder,/select plan\\\(12\\\)/);assert.match(builder,/select plan\\\(24\\\)/);assert.match(builder,/select plan\(36\)/);assert.match(builder,/M23_G3_0049_TRANSACTION_36_OF_36_ROLLBACK/);assert.match(builder,/M23_G3_0049_PGTAP_FAILED/);assert.match(runner,/M23_G3_0049_TRANSACTION_36_OF_36_ROLLBACK/);assert.match(runner,/0049_m23_g3_academy_auto_activation/);assert.match(runner,/regressao 0048 adversarial 25\/25/)});
test('pgTAP declara 12 + 24 assercoes e rollback',()=>{assert.match(structural,/select plan\(12\)/);assert.match(adversarial,/select plan\(24\)/);assert.match(structural,/select\s*\*\s*from\s+finish\(\);\s*rollback;/);assert.match(adversarial,/select\s*\*\s*from\s+finish\(\);\s*rollback;/)});
test('cenarios adversariais cobrem os aceites de capacidade e alvo',()=>{for(const s of ['exception deny remove o vinculo','exception allow liga H','janela vencida derruba F','esta suspenso e fica de fora','resync no estado atual nao muda nada','ressincronia preserva o vinculo manual','dono perde a chave'])assert.ok(adversarial.includes(s),`${s} ausente`);assert.match(adversarial,/95000000-0000-4000-8000-000000000001/);assert.doesNotMatch(adversarial,/92000000-0000-4000-8000-000000000001/)});
test('o adversarial da 0048 passou a esperar 2 vinculos (so com capacidade)',()=>{assert.match(adversarial0048,/2::bigint,'sincronia liga so as empresas com a capacidade/);assert.doesNotMatch(adversarial0048,/3::bigint,'sincronia liga as 3 empresas/)});
test('verificacao pos-apply observa gatilhos, grants e marcador final',()=>{assert.match(post,/M23_G3_POST_APPLY_OK::academy_capability_sync/);assert.match(post,/trg_academy_capabilities_sync/);assert.match(post,/anon_must_be_false/);assert.match(post,/academy_capability/)});
test('nenhuma identidade real foi incluida nos artefatos',()=>{for(const text of[migration,preflight,rollback,structural,adversarial,post])assert.doesNotMatch(text,/09[.\/-]?050[.\/-]?756|@(?:gmail|hotmail|outlook|ig)\./i)});
