import { createHash, sign as cryptoSign, verify as cryptoVerify } from 'node:crypto';

export const PROTOCOL_VERSION = '1.0';
export const MESSAGE_TYPES = Object.freeze(['agent.heartbeat','device.inventory','print.execute','scale.read','cash_drawer.open','tef.execute','offline.snapshot.ack','offline.operation.push','command.result']);
const forbiddenKey=/(password|passphrase|access.?token|refresh.?token|service.?role|private.?key|certificate|cvv|full.?pan|magnetic.?track|pin.?block|secret|credential)/i;
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
const nonce=/^[A-Za-z0-9_-]{22,128}$/;const sha256=/^[0-9a-f]{64}$/;

export class ProtocolValidationError extends Error{constructor(code,message){super(`${code}: ${message}`);this.name='ProtocolValidationError';this.code=code}}
function assertObject(value,label){if(!value||typeof value!=='object'||Array.isArray(value))throw new ProtocolValidationError('INVALID_OBJECT',`${label} deve ser objeto`)}
function rejectSecrets(value,path='payload'){if(Array.isArray(value))return value.forEach((item,index)=>rejectSecrets(item,`${path}[${index}]`));if(!value||typeof value!=='object')return;for(const[key,nested]of Object.entries(value)){if(forbiddenKey.test(key))throw new ProtocolValidationError('SECRET_FIELD_FORBIDDEN',`${path}.${key}`);rejectSecrets(nested,`${path}.${key}`)}}
export function canonicalize(value){if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return`[${value.map(canonicalize).join(',')}]`;return`{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonicalize(value[key])}`).join(',')}}`}
export function unsignedEnvelope(envelope){const{signature:_signature,...unsigned}=envelope;return unsigned}

export function validateEnvelope(envelope,options={}){assertObject(envelope,'envelope');for(const field of['messageId','tenantId','establishmentId','agentId'])if(!uuid.test(envelope[field]??''))throw new ProtocolValidationError('INVALID_UUID',field);if(envelope.protocolVersion!==PROTOCOL_VERSION)throw new ProtocolValidationError('UNSUPPORTED_VERSION','versão não suportada');if(!MESSAGE_TYPES.includes(envelope.type))throw new ProtocolValidationError('INVALID_MESSAGE_TYPE',envelope.type??'ausente');if(!nonce.test(envelope.nonce??''))throw new ProtocolValidationError('INVALID_NONCE','nonce inválido');if(typeof envelope.idempotencyKey!=='string'||envelope.idempotencyKey.length<8||envelope.idempotencyKey.length>200)throw new ProtocolValidationError('INVALID_IDEMPOTENCY_KEY','tamanho inválido');if(typeof envelope.keyId!=='string'||envelope.keyId.length<8||envelope.keyId.length>100)throw new ProtocolValidationError('INVALID_KEY_ID','keyId inválido');assertObject(envelope.payload,'payload');rejectSecrets(envelope.payload);const issuedAt=Date.parse(envelope.issuedAt),expiresAt=Date.parse(envelope.expiresAt),now=options.now instanceof Date?options.now.getTime():Date.now();if(!Number.isFinite(issuedAt)||!Number.isFinite(expiresAt))throw new ProtocolValidationError('INVALID_TIME','datas inválidas');if(expiresAt<=issuedAt||expiresAt-issuedAt>300000)throw new ProtocolValidationError('INVALID_TTL','TTL deve ser de até cinco minutos');if(issuedAt>now+30000)throw new ProtocolValidationError('FUTURE_MESSAGE','issuedAt excede tolerância');if(expiresAt<=now)throw new ProtocolValidationError('EXPIRED_MESSAGE','mensagem expirada');if(options.expectedTenantId&&envelope.tenantId!==options.expectedTenantId)throw new ProtocolValidationError('TENANT_MISMATCH','tenant divergente');if(options.expectedAgentId&&envelope.agentId!==options.expectedAgentId)throw new ProtocolValidationError('AGENT_MISMATCH','agente divergente');return envelope}
export function signEnvelope(envelope,privateKey,options={}){validateEnvelope(envelope,options);const data=Buffer.from(canonicalize(unsignedEnvelope(envelope)));return{...unsignedEnvelope(envelope),signature:cryptoSign(null,data,privateKey).toString('base64url')}}
export function verifyEnvelope(envelope,publicKey,options={}){validateEnvelope(envelope,options);if(typeof envelope.signature!=='string'||envelope.signature.length<80)throw new ProtocolValidationError('INVALID_SIGNATURE','assinatura ausente');const data=Buffer.from(canonicalize(unsignedEnvelope(envelope)));if(!cryptoVerify(null,data,publicKey,Buffer.from(envelope.signature,'base64url')))throw new ProtocolValidationError('INVALID_SIGNATURE','assinatura não confere');if(options.replayStore){const replayKey=`${envelope.agentId}:${envelope.nonce}`;if(options.replayStore.has(replayKey))throw new ProtocolValidationError('REPLAY_DETECTED','nonce reutilizado');options.replayStore.add(replayKey,envelope.expiresAt)}return true}
export class MemoryReplayStore{#entries=new Map();has(key){return this.#entries.has(key)}add(key,expiresAt){this.#entries.set(key,expiresAt)}purge(now=new Date()){for(const[key,expiresAt]of this.#entries)if(Date.parse(expiresAt)<=now.getTime())this.#entries.delete(key)}}
export function hashOfflineOperation(operation){assertObject(operation,'operation');if(!uuid.test(operation.operationId??''))throw new ProtocolValidationError('INVALID_UUID','operationId');if(operation.previousHash!==null&&!sha256.test(operation.previousHash??''))throw new ProtocolValidationError('INVALID_PREVIOUS_HASH','previousHash inválido');rejectSecrets(operation);const{operationHash:_operationHash,...unsigned}=operation;return createHash('sha256').update(canonicalize(unsigned)).digest('hex')}
export function validateOfflineChain(operations){if(!Array.isArray(operations))throw new ProtocolValidationError('INVALID_CHAIN','operações devem ser array');let previousHash=null;const ids=new Set();for(const operation of operations){if(ids.has(operation.operationId))throw new ProtocolValidationError('DUPLICATE_OPERATION',operation.operationId);if(operation.previousHash!==previousHash)throw new ProtocolValidationError('BROKEN_CHAIN',operation.operationId);const calculated=hashOfflineOperation(operation);if(operation.operationHash!==calculated)throw new ProtocolValidationError('INVALID_OPERATION_HASH',operation.operationId);ids.add(operation.operationId);previousHash=calculated}return true}
