import{z}from'zod';
export const unitSchema=z.object({code:z.string().trim().toUpperCase().regex(/^[A-Z0-9]{1,12}$/,'Código de unidade inválido.'),name:z.string().trim().min(2).max(80),dimension:z.enum(['count','mass','length','volume','area','time','other']),decimal_scale:z.coerce.number().int().min(0).max(6)});
export const itemSchema=z.object({code:z.string().trim().min(1).max(64),name:z.string().trim().min(2).max(180),description:z.string().trim().max(1000).optional(),kind:z.enum(['product','service','part','ingredient','prepared','kit','supply','fee','voucher']),base_unit_id:z.string().uuid(),track_inventory:z.boolean(),allows_fraction:z.boolean()}).refine(v=>!(['service','fee','voucher'].includes(v.kind)&&v.track_inventory),{message:'Serviço, taxa e vale não controlam estoque.'});
// M20-G1/G3 — aba Fiscal, mesmo universo CST/CSOSN de packages/fiscal-contract/src/tax-profiles.mjs.
const CST_CODES=['00','10','20','30','40','41','50','51','60','70','90'] as const;
const CSOSN_CODES=['101','102','103','201','202','203','300','400','500','900'] as const;
export const itemFiscalSchema=z.object({item_id:z.string().uuid(),ncm:z.string().trim().regex(/^\d{8}$/,'NCM deve ter 8 dígitos.'),cest:z.string().trim().regex(/^\d{7}$/,'CEST deve ter 7 dígitos.').optional().or(z.literal('')),origin:z.coerce.number().int().min(0).max(8),tax_code_kind:z.enum(['CST','CSOSN']),tax_code:z.string().trim(),icms_rate:z.coerce.number().min(0).max(100),icms_base_percent:z.coerce.number().min(0).max(100),ipi_rate:z.coerce.number().min(0).max(100),gross_weight:z.coerce.number().min(0).optional(),net_weight:z.coerce.number().min(0).optional()}).refine(v=>v.tax_code_kind==='CST'?(CST_CODES as readonly string[]).includes(v.tax_code):(CSOSN_CODES as readonly string[]).includes(v.tax_code),{message:'Código CST/CSOSN não pertence ao regime selecionado.',path:['tax_code']}).refine(v=>v.gross_weight===undefined||v.net_weight===undefined||v.net_weight<=v.gross_weight,{message:'Peso líquido não pode ser maior que o peso bruto.',path:['net_weight']});
// M20-G1/G3 — aba Comercial.
export const itemCommercialSchema=z.object({item_id:z.string().uuid(),cost_price:z.coerce.number().min(0),margin_percent:z.coerce.number().min(0),suggested_sale_price:z.coerce.number().min(0).optional(),min_stock_quantity:z.coerce.number().min(0),reorder_point:z.coerce.number().min(0).optional()}).refine(v=>v.reorder_point===undefined||v.reorder_point>=v.min_stock_quantity,{message:'Ponto de reposição não pode ser menor que o estoque mínimo.',path:['reorder_point']});
