'use client';
import { useState } from 'react';import { useActionState } from 'react';import { useFormStatus } from 'react-dom';import{createItemAction,createUnitAction,type CatalogState}from'../actions';import type{ItemKind,Unit}from'../types';const initial:CatalogState={error:null,success:false};
function Submit({label}:{label:string}){const{pending}=useFormStatus();return <button className="pf-button" type="submit" disabled={pending}>{pending?'Salvando…':label}</button>}
export function UnitForm(){const[s,a]=useActionState(createUnitAction,initial);return <div className="pf-content-card"><h2>Nova unidade</h2><form action={a}><div className="pf-grid-2"><div className="pf-field"><label htmlFor="unit-code">Código</label><input id="unit-code" name="code" placeholder="UN" required/></div><div className="pf-field"><label htmlFor="unit-name">Nome</label><input id="unit-name" name="name" placeholder="Unidade" required/></div><div className="pf-field"><label htmlFor="dimension">Dimensão</label><select id="dimension" name="dimension" defaultValue="count"><option value="count">Contagem</option><option value="mass">Massa</option><option value="length">Comprimento</option><option value="volume">Volume</option><option value="area">Área</option><option value="time">Tempo</option><option value="other">Outra</option></select></div><div className="pf-field"><label htmlFor="decimal_scale">Casas decimais</label><input id="decimal_scale" name="decimal_scale" type="number" min="0" max="6" defaultValue="0"/></div></div>{s.error&&<p className="pf-error">{s.error}</p>}{s.success&&<p className="pf-success">Unidade criada.</p>}<Submit label="Salvar unidade"/></form></div>}
// M20-G6 — eleva o esqueleto de aceite de gate a tela real de uso: tipo "Serviço/Taxa/Vale"
// desliga e trava "Controla estoque" ao vivo, em vez de só reprovar depois do envio (a
// regra de negócio é a mesma do zod em validations.ts — aqui é só refletir na UI antes).
const NO_INVENTORY_KINDS=new Set<ItemKind>(['service','fee','voucher']);
export function ItemForm({units}:{units:Unit[]}){const[s,a]=useActionState(createItemAction,initial);const[kind,setKind]=useState<ItemKind>('product');const tracksInventory=!NO_INVENTORY_KINDS.has(kind);return <div className="pf-content-card"><h2>Novo item universal</h2>{!units.length?<p className="pf-notice">Cadastre ao menos uma unidade antes do primeiro item.</p>:<form action={a}><div className="pf-grid-2"><div className="pf-field"><label htmlFor="item-code">Código</label><input id="item-code" name="code" required/></div><div className="pf-field"><label htmlFor="item-name">Nome</label><input id="item-name" name="name" required/></div><div className="pf-field"><label htmlFor="kind">Tipo</label><select id="kind" name="kind" value={kind} onChange={(e)=>setKind(e.target.value as ItemKind)}><option value="product">Produto</option><option value="service">Serviço</option><option value="part">Peça</option><option value="ingredient">Ingrediente</option><option value="prepared">Preparado</option><option value="kit">Kit</option><option value="supply">Insumo</option><option value="fee">Taxa</option><option value="voucher">Vale</option></select></div><div className="pf-field"><label htmlFor="base_unit_id">Unidade base</label><select id="base_unit_id" name="base_unit_id">{units.map(u=><option value={u.id} key={u.id}>{u.code} — {u.name}</option>)}</select></div></div><div className="pf-field"><label htmlFor="description">Descrição</label><textarea id="description" name="description"/></div><div className="pf-inline-actions"><label title={tracksInventory?undefined:'Serviço, taxa e vale não controlam estoque.'}><input type="checkbox" name="track_inventory" disabled={!tracksInventory} key={tracksInventory?'on':'off'}/> Controla estoque{!tracksInventory&&' (não se aplica a este tipo)'}</label><label><input type="checkbox" name="allows_fraction"/> Aceita fração</label></div>{s.error&&<p className="pf-error">{s.error}</p>}{s.success&&<p className="pf-success">Item criado.</p>}<Submit label="Salvar item"/></form>}</div>}
