param([switch]$SelfTest)
$ErrorActionPreference='Stop'
$targets=@(
@{Name='SP';Url='https://homologacao.nfe.fazenda.sp.gov.br/ws/nfestatusservico4.asmx';CUF='35'},
@{Name='SVRS';Url='https://nfe-homologacao.svrs.rs.gov.br/ws/NfeStatusServico/NfeStatusServico4.asmx';CUF='33'},
@{Name='SVAN';Url='https://hom.sefazvirtual.fazenda.gov.br/NFeStatusServico4/NFeStatusServico4.asmx';CUF='21'}
)
function New-StatusEnvelope($cUF){return('<soap12:Envelope xmlns:soap12="http://www.w3.org/2003/05/soap-envelope"><soap12:Body><nfeDadosMsg xmlns="http://www.portalfiscal.inf.br/nfe/wsdl/NFeStatusServico4"><consStatServ xmlns="http://www.portalfiscal.inf.br/nfe" versao="4.00"><tpAmb>2</tpAmb><cUF>'+ $cUF +'</cUF><xServ>STATUS</xServ></consStatServ></nfeDadosMsg></soap12:Body></soap12:Envelope>')}
if($SelfTest){$xml=New-StatusEnvelope '35';if($xml -match '<CNPJ|<CPF|<chNFe|<infNFe'){throw 'SELF_TEST_SCOPE_FAILED'};Write-Host 'M13_G15_STATUS_SELF_TEST_OK';exit 0}
Add-Type -AssemblyName System.Net.Http;Add-Type -AssemblyName System.Security
$store=New-Object System.Security.Cryptography.X509Certificates.X509Store([System.Security.Cryptography.X509Certificates.StoreName]::My,[System.Security.Cryptography.X509Certificates.StoreLocation]::CurrentUser)
try{$store.Open([System.Security.Cryptography.X509Certificates.OpenFlags]::ReadOnly);$now=[DateTime]::UtcNow;$candidates=New-Object System.Security.Cryptography.X509Certificates.X509Certificate2Collection;foreach($certificate in $store.Certificates){if($certificate.HasPrivateKey -and $certificate.NotBefore.ToUniversalTime() -le $now -and $certificate.NotAfter.ToUniversalTime() -ge $now){[void]$candidates.Add($certificate)}};$selected=[System.Security.Cryptography.X509Certificates.X509Certificate2UI]::SelectFromCollection($candidates,'Select A1 for NFeStatusServico4 homologation','Status query only. No NF-e, NFC-e, key, identity or fiscal data.',[System.Security.Cryptography.X509Certificates.X509SelectionFlag]::SingleSelection);if($selected.Count -ne 1){Write-Host 'M13_G15_CANCELLED';exit 2};foreach($target in $targets){$handler=New-Object System.Net.Http.HttpClientHandler;[void]$handler.ClientCertificates.Add($selected[0]);$client=New-Object System.Net.Http.HttpClient($handler);$client.Timeout=[TimeSpan]::FromSeconds(15);try{$xml=New-StatusEnvelope $target.CUF;$content=New-Object System.Net.Http.StringContent($xml,[Text.Encoding]::UTF8,'application/soap+xml');$response=$client.PostAsync($target.Url,$content).GetAwaiter().GetResult();$body=$response.Content.ReadAsStringAsync().GetAwaiter().GetResult();$cStat=[regex]::Match($body,'<cStat>([^<]+)</cStat>').Groups[1].Value;if([string]::IsNullOrWhiteSpace($cStat)){$cStat='none'};Write-Host ('M13_G15_STATUS_RESULT authorizer={0} http={1} cStat={2} identitySent=false documentSent=false production=false' -f $target.Name,[int]$response.StatusCode,$cStat)}catch{Write-Host ('M13_G15_STATUS_FAIL authorizer={0} errorType={1} identitySent=false documentSent=false production=false' -f $target.Name,$_.Exception.GetType().Name)}finally{$client.Dispose();$handler.Dispose()}}}finally{$store.Close();Remove-Variable xml,body,content,response -ErrorAction SilentlyContinue}
