'use client';
import{useMemo,useState}from'react';
import{capabilityDefinitions,profileBlueprints,syntheticTenants}from'../presentation';
import type{CapabilityEffect,CapabilityException,CapabilityStatus}from'../types';
const statusLabel:Record<CapabilityStatus,string>={enabled:'Habilitado',disabled:'Desabilitado',blocked:'Bloqueado'};
export function CapabilityAdminDemo(){
 const[tenantId,setTenantId]=useState(syntheticTenants[1].id),[capabilityKey,setCapabilityKey]=useState('inventory.stock'),[effect,setEffect]=useState<CapabilityEffect>('deny'),[exceptions,setExceptions]=useState<CapabilityException[]>([]),[readiness,setReadiness]=useState<Record<string,boolean>>({});
 const tenant=syntheticTenants.find(item=>item.id===tenantId)??syntheticTenants[0];
 const rows=useMemo(()=>capabilityDefinitions.map(capability=>{const active=exceptions.filter(item=>item.tenantId===tenant.id&&item.capabilityKey===capability.key&&item.active),denied=active.some(item=>item.effect==='deny'),allowed=active.some(item=>item.effect==='allow'),contracted=profileBlueprints[tenant.profile].includes(capability.key),effective=denied?false:allowed||contracted,status:CapabilityStatus=effective?(capability.critical&&readiness[`${tenant.id}:${capability.key}`]!==true?'blocked':'enabled'):'disabled',source=denied?'Exceção deny':allowed?'Exceção allow':contracted?`Blueprint ${tenant.profile}`:'Default deny';return{...capability,status,source}}),[exceptions,readiness,tenant]);
 const addException=()=>setExceptions(current=>[{id:`SYNTHETIC-EX-${String(current.length+1).padStart(3,'0')}`,tenantId:tenant.id,capabilityKey,effect,expiresAt:'31/12/2026',active:true},...current]),revoke=(id:string)=>setExceptions(current=>current.map(item=>item.id===id?{...item,active:false}:item)),toggleReadiness=(key:string)=>setReadiness(current=>({...current,[`${tenant.id}:${key}`]:!current[`${tenant.id}:${key}`]})),counts=rows.reduce((result,row)=>({...result,[row.status]:result[row.status]+1}),{enabled:0,disabled:0,blocked:0}as Record<CapabilityStatus,number>),tenantExceptions=exceptions.filter(item=>item.tenantId===tenant.id);
 return <><div className="pf-page-header"><div><div className="pf-eyebrow">M16-G7 · demonstração local</div><h1>Capacidades, planos e exceções</h1><p>Simule o contrato de cada empresa sem alterar banco, usuários ou produção.</p></div><span className="pf-capability-mode">Somente memória</span></div><div className="pf-capability-warning" role="status"><strong>Dados totalmente sintéticos.</strong> Alterações desaparecem ao recarregar; nenhuma ação chama Supabase, API ou serviço remoto.</div>
 <section className="pf-capability-toolbar"><label>Empresa sintética<select value={tenantId} onChange={event=>setTenantId(event.target.value)}>{syntheticTenants.map(item=><option value={item.id} key={item.id}>{item.name} · {item.profile}</option>)}</select></label><div><span>Perfil jurídico</span><strong>{tenant.profile}</strong></div><div><span>Contrato</span><strong>Blueprint v1</strong></div></section>
 <section className="pf-capability-metrics" aria-label="Resumo das capacidades"><article><strong>{counts.enabled}</strong><span>habilitadas</span></article><article><strong>{counts.disabled}</strong><span>desabilitadas</span></article><article><strong>{counts.blocked}</strong><span>bloqueadas</span></article><article><strong>{tenantExceptions.filter(item=>item.active).length}</strong><span>exceções ativas</span></article></section>
 <div className="pf-capability-layout"><section className="pf-content-card"><div className="pf-card-head"><div><div className="pf-eyebrow">Matriz efetiva</div><h2>{tenant.name}</h2></div><span className="pf-pill">deny prevalece</span></div><div className="pf-capability-table-wrap"><table className="pf-capability-table"><thead><tr><th>Capacidade</th><th>Grupo</th><th>Origem</th><th>Estado</th><th>Prontidão</th></tr></thead><tbody>{rows.map(row=><tr key={row.key}><td><strong>{row.name}</strong><code>{row.key}</code></td><td>{row.group}</td><td>{row.source}</td><td><span className={`pf-capability-status ${row.status}`}>{statusLabel[row.status]}</span></td><td>{row.critical?<button type="button" className="pf-link-btn" onClick={()=>toggleReadiness(row.key)}>{readiness[`${tenant.id}:${row.key}`]?'Revogar prontidão':'Validar sinteticamente'}</button>:<span className="pf-muted">Não exigida</span>}</td></tr>)}</tbody></table></div></section>
 <aside className="pf-content-card pf-capability-aside"><div className="pf-eyebrow">Nova exceção</div><h2>Alteração temporária</h2><label>Capacidade<select value={capabilityKey} onChange={event=>setCapabilityKey(event.target.value)}>{capabilityDefinitions.map(item=><option value={item.key} key={item.key}>{item.name}</option>)}</select></label><label>Efeito<select value={effect} onChange={event=>setEffect(event.target.value as CapabilityEffect)}><option value="deny">deny · bloquear</option><option value="allow">allow · habilitar</option></select></label><label>Expiração<input value="31/12/2026" disabled/></label><button className="pf-button" type="button" onClick={addException}>Aplicar na sessão</button><small>Justificativa e aprovação são representadas por hashes sintéticos.</small><div className="pf-capability-exceptions"><h3>Exceções da empresa</h3>{tenantExceptions.length===0?<p className="pf-muted">Nenhuma exceção nesta sessão.</p>:tenantExceptions.map(item=><article key={item.id} className={!item.active?'revoked':''}><div><strong>{item.effect}</strong><code>{item.capabilityKey}</code><small>{item.id} · até {item.expiresAt}</small></div><button type="button" disabled={!item.active} onClick={()=>revoke(item.id)}>{item.active?'Revogar':'Revogada'}</button></article>)}</div></aside></div></>;
}
