begin;
drop policy if exists fd_storage_insert on storage.objects;
drop policy if exists fd_storage_select on storage.objects;
drop policy if exists fd_storage_no_update on storage.objects;
drop policy if exists fd_storage_no_delete on storage.objects;
drop policy if exists fd_storage_anon_guard on storage.objects;
delete from storage.buckets where id = 'fiscal-deliveries';
drop function if exists public.erp_publish_accountant_package(uuid,date,jsonb,text);
drop function if exists public.erp_list_accountant_packages(uuid,integer);
drop function if exists public.erp_ack_accountant_package(uuid,uuid,text,text);
drop function if exists public.erp_void_accountant_package(uuid,uuid,text,text);
drop function if exists public.erp_log_accountant_download(uuid,uuid,integer);
drop function if exists public.is_accountant();
drop table if exists public.erp_accountant_delivery_events;
drop table if exists public.erp_accountant_package_files;
drop table if exists public.erp_accountant_packages;
delete from public.erp_permissions where key = 'fiscal.deliver';
delete from public.user_roles where role_id = (select id from public.roles where nome = 'contador');
delete from public.roles where nome = 'contador';
commit;
