-- ConnectionCyber — M11: atendimento, SLA, dispositivos e acesso remoto consentido.
begin;
create table public.erp_support_queues(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,code text not null,name text not null,active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code),unique(tenant_id,id));
create table public.erp_support_queue_members(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,queue_id uuid not null,user_id uuid not null references auth.users(id),active boolean not null default true,created_at timestamptz not null default now(),unique(tenant_id,queue_id,user_id),unique(tenant_id,id),foreign key(tenant_id,queue_id) references public.erp_support_queues(tenant_id,id) on delete cascade);
create table public.erp_sla_policies(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,code text not null,name text not null,version integer not null check(version>0),timezone text not null default 'America/Sao_Paulo',active boolean not null default true,effective_from timestamptz not null default now(),effective_until timestamptz,created_at timestamptz not null default now(),unique(tenant_id,code,version),unique(tenant_id,id),check(effective_until is null or effective_until>effective_from));
create table public.erp_sla_targets(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,sla_policy_id uuid not null,priority text not null check(priority in('low','normal','high','urgent')),first_response_minutes integer not null check(first_response_minutes>0),resolution_minutes integer not null check(resolution_minutes>0),pause_on_customer boolean not null default true,created_at timestamptz not null default now(),unique(tenant_id,sla_policy_id,priority),unique(tenant_id,id),foreign key(tenant_id,sla_policy_id) references public.erp_sla_policies(tenant_id,id) on delete cascade);
create table public.erp_support_tickets(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,party_id uuid not null,asset_id uuid,queue_id uuid,sla_policy_id uuid,merged_into_id uuid,code text not null,subject text not null,description text not null,priority text not null default 'normal' check(priority in('low','normal','high','urgent')),status text not null default 'new' check(status in('new','triaged','assigned','in_progress','waiting_customer','waiting_internal','resolved','closed','cancelled','reopened','merged')),source text not null default 'platform' check(source in('portal','platform','email','phone','integration')),idempotency_key text not null,created_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),resolved_at timestamptz,closed_at timestamptz,unique(tenant_id,code),unique(tenant_id,idempotency_key),unique(tenant_id,id),foreign key(tenant_id,party_id) references public.erp_parties(tenant_id,id) on delete restrict,foreign key(tenant_id,asset_id) references public.erp_assets(tenant_id,id) on delete restrict,foreign key(tenant_id,queue_id) references public.erp_support_queues(tenant_id,id) on delete restrict,foreign key(tenant_id,sla_policy_id) references public.erp_sla_policies(tenant_id,id) on delete restrict,foreign key(tenant_id,merged_into_id) references public.erp_support_tickets(tenant_id,id) on delete restrict);
create table public.erp_support_ticket_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,event_type text not null,from_status text,to_status text,detail jsonb not null default '{}'::jsonb,reason text,idempotency_key text not null,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,idempotency_key),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete restrict,check(detail::text!~*'"(password|access_token|refresh_token|service_role|secret|credential|private_key)"[[:space:]]*:'));
create table public.erp_support_messages(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,visibility text not null check(visibility in('customer','internal')),body text not null check(length(body)between 1 and 20000),idempotency_key text not null,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,idempotency_key),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete restrict);
create table public.erp_support_attachments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,message_id uuid,storage_bucket text not null,storage_path text not null,content_hash text check(content_hash is null or content_hash~'^[a-f0-9]{64}$'),created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,storage_bucket,storage_path),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete cascade,foreign key(tenant_id,message_id) references public.erp_support_messages(tenant_id,id) on delete cascade,check(storage_path not like '%..%'));
create table public.erp_ticket_assignments(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,technician_id uuid not null references auth.users(id),status text not null default 'active' check(status in('active','released')),assigned_at timestamptz not null default now(),released_at timestamptz,idempotency_key text not null,assigned_by uuid references auth.users(id),unique(tenant_id,idempotency_key),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete restrict,check((status='released' and released_at is not null)or status='active'));
create unique index erp_ticket_assignments_one_active on public.erp_ticket_assignments(tenant_id,ticket_id)where status='active';
create table public.erp_ticket_sla_clocks(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,metric text not null check(metric in('first_response','resolution')),status text not null default 'running' check(status in('running','paused','met','breached','cancelled')),deadline_at timestamptz not null,met_at timestamptz,accumulated_pause_seconds bigint not null default 0 check(accumulated_pause_seconds>=0),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,ticket_id,metric),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete cascade);
create table public.erp_managed_devices(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,asset_id uuid,party_id uuid,code text not null,name text not null,status text not null default 'pending' check(status in('pending','active','offline','suspended','revoked')),agent_version text,last_seen_at timestamptz,capabilities jsonb not null default '[]'::jsonb check(jsonb_typeof(capabilities)='array'),paired_at timestamptz,revoked_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(tenant_id,code),unique(tenant_id,id),foreign key(tenant_id,asset_id) references public.erp_assets(tenant_id,id) on delete restrict,foreign key(tenant_id,party_id) references public.erp_parties(tenant_id,id) on delete restrict);
create table public.erp_device_identifiers(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,device_id uuid not null,kind text not null check(kind in('agent','hardware','hostname_hash','certificate_thumbprint')),value_hash text not null check(value_hash~'^[a-f0-9]{64}$'),created_at timestamptz not null default now(),unique(tenant_id,kind,value_hash),unique(tenant_id,id),foreign key(tenant_id,device_id) references public.erp_managed_devices(tenant_id,id) on delete cascade);
create table public.erp_remote_consents(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,device_id uuid not null,granted_by_party_id uuid not null,technician_id uuid,scope text[] not null check(cardinality(scope)>0),purpose text not null,status text not null default 'pending' check(status in('pending','granted','denied','revoked','expired')),text_version text not null,channel text not null check(channel in('portal','in_person','phone','other')),valid_from timestamptz,expires_at timestamptz,decided_at timestamptz,revoked_at timestamptz,idempotency_key text not null,created_at timestamptz not null default now(),unique(tenant_id,idempotency_key),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete restrict,foreign key(tenant_id,device_id) references public.erp_managed_devices(tenant_id,id) on delete restrict,foreign key(tenant_id,granted_by_party_id) references public.erp_parties(tenant_id,id) on delete restrict,check(expires_at is null or valid_from is null or expires_at>valid_from));
create table public.erp_remote_access_grants(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,ticket_id uuid not null,device_id uuid not null,consent_id uuid not null,technician_id uuid not null references auth.users(id),scope text[] not null check(cardinality(scope)>0),audience text not null,token_hash text not null check(token_hash~'^[a-f0-9]{64}$'),status text not null default 'issued' check(status in('issued','consumed','expired','revoked')),issued_at timestamptz not null default now(),expires_at timestamptz not null,consumed_at timestamptz,revoked_at timestamptz,idempotency_key text not null,created_at timestamptz not null default now(),unique(tenant_id,idempotency_key),unique(tenant_id,token_hash),unique(tenant_id,id),foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete restrict,foreign key(tenant_id,device_id) references public.erp_managed_devices(tenant_id,id) on delete restrict,foreign key(tenant_id,consent_id) references public.erp_remote_consents(tenant_id,id) on delete restrict,check(expires_at>issued_at));
create table public.erp_remote_sessions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,grant_id uuid not null,ticket_id uuid not null,device_id uuid not null,technician_id uuid not null references auth.users(id),status text not null default 'requested' check(status in('requested','authorized','connecting','active','ended','denied','failed','revoked','expired')),gateway_session_reference text,started_at timestamptz,ended_at timestamptz,last_heartbeat_at timestamptz,idempotency_key text not null,created_at timestamptz not null default now(),unique(tenant_id,idempotency_key),unique(tenant_id,grant_id),unique(tenant_id,id),foreign key(tenant_id,grant_id) references public.erp_remote_access_grants(tenant_id,id) on delete restrict,foreign key(tenant_id,ticket_id) references public.erp_support_tickets(tenant_id,id) on delete restrict,foreign key(tenant_id,device_id) references public.erp_managed_devices(tenant_id,id) on delete restrict,check(ended_at is null or started_at is null or ended_at>=started_at));
create table public.erp_remote_session_events(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,session_id uuid not null,event_type text not null,from_status text,to_status text,detail jsonb not null default '{}'::jsonb,idempotency_key text not null,created_by uuid references auth.users(id),created_at timestamptz not null default now(),unique(tenant_id,idempotency_key),unique(tenant_id,id),foreign key(tenant_id,session_id) references public.erp_remote_sessions(tenant_id,id) on delete restrict,check(detail::text!~*'"(password|token|secret|credential|private_key|clipboard)"[[:space:]]*:'));
create table public.erp_remote_session_artifacts(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id) on delete cascade,session_id uuid not null,kind text not null check(kind in('audit_log','recording','diagnostic','other')),storage_bucket text not null,storage_path text not null,content_hash text check(content_hash is null or content_hash~'^[a-f0-9]{64}$'),retention_until date,consent_id uuid,created_at timestamptz not null default now(),unique(tenant_id,storage_bucket,storage_path),unique(tenant_id,id),foreign key(tenant_id,session_id) references public.erp_remote_sessions(tenant_id,id) on delete restrict,foreign key(tenant_id,consent_id) references public.erp_remote_consents(tenant_id,id) on delete restrict,check(storage_path not like '%..%'));

insert into public.erp_permissions(key,name,description,category)values('support.read','Consultar atendimento','Consulta tickets, filas e SLA.','Atendimento'),('support.create','Criar tickets','Abre tickets no tenant.','Atendimento'),('support.manage','Gerenciar tickets','Triagem e transições de tickets.','Atendimento'),('support.assign','Atribuir tickets','Atribui técnicos e filas.','Atendimento'),('support.sla','Gerenciar SLA','Mantém políticas e relógios de SLA.','Atendimento'),('remote.request','Solicitar acesso remoto','Registra consentimentos e solicitações.','Acesso remoto'),('remote.connect','Conectar remotamente','Emite grants sob MFA AAL2.','Acesso remoto'),('remote.revoke','Revogar acesso remoto','Revoga grants e sessões.','Acesso remoto'),('remote.audit','Auditar acesso remoto','Consulta eventos e artefatos.','Acesso remoto')on conflict(key)do update set name=excluded.name,description=excluded.description,category=excluded.category,active=true;

create or replace function public.erp_create_support_ticket(p_tenant_id uuid,p_party_id uuid,p_asset_id uuid,p_code text,p_subject text,p_description text,p_priority text,p_source text,p_idempotency_key text)returns uuid language plpgsql security definer set search_path='' as $$declare v_id uuid;begin if not(erp_security.has_permission(p_tenant_id,'support.create')or public.is_platform_staff())then raise exception 'permission denied';end if;select id into v_id from public.erp_support_tickets where tenant_id=p_tenant_id and idempotency_key=p_idempotency_key;if v_id is not null then return v_id;end if;insert into public.erp_support_tickets(tenant_id,party_id,asset_id,code,subject,description,priority,source,idempotency_key,created_by)values(p_tenant_id,p_party_id,p_asset_id,p_code,btrim(p_subject),btrim(p_description),p_priority,p_source,p_idempotency_key,auth.uid())returning id into v_id;insert into public.erp_support_ticket_events(tenant_id,ticket_id,event_type,to_status,idempotency_key,created_by)values(p_tenant_id,v_id,'created','new',p_idempotency_key||':event',auth.uid());return v_id;end$$;
create or replace function public.erp_issue_remote_access_grant(p_tenant_id uuid,p_ticket_id uuid,p_device_id uuid,p_consent_id uuid,p_scope text[],p_audience text,p_idempotency_key text)returns table(grant_id uuid,access_token text)language plpgsql security definer set search_path='' as $$declare v_existing uuid;v_token text;begin if erp_security.current_aal()<>'aal2'or not(erp_security.has_permission(p_tenant_id,'remote.connect')or public.is_platform_staff())then raise exception 'permission and aal2 required';end if;if cardinality(p_scope)not between 1 and 20 or exists(select 1 from unnest(p_scope)s where length(btrim(s))not between 1 and 64)then raise exception 'invalid scope';end if;if length(btrim(p_audience))not between 1 and 200 or length(btrim(p_idempotency_key))not between 8 and 200 then raise exception 'invalid audience or idempotency key';end if;select id into v_existing from public.erp_remote_access_grants where tenant_id=p_tenant_id and idempotency_key=p_idempotency_key;if v_existing is not null then return query select v_existing,null::text;return;end if;perform pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':'||p_ticket_id::text||':'||p_device_id::text,0));if not exists(select 1 from public.erp_support_tickets where tenant_id=p_tenant_id and id=p_ticket_id and status in('assigned','in_progress','waiting_customer','waiting_internal','reopened'))then raise exception 'ticket not eligible';end if;if not exists(select 1 from public.erp_managed_devices where tenant_id=p_tenant_id and id=p_device_id and status='active')then raise exception 'device not active';end if;if not exists(select 1 from public.erp_remote_consents where tenant_id=p_tenant_id and id=p_consent_id and ticket_id=p_ticket_id and device_id=p_device_id and status='granted' and valid_from<=now()and expires_at>now()and p_scope<@scope)then raise exception 'valid consent required';end if;v_token:=encode(gen_random_bytes(32),'hex');insert into public.erp_remote_access_grants(tenant_id,ticket_id,device_id,consent_id,technician_id,scope,audience,token_hash,expires_at,idempotency_key)values(p_tenant_id,p_ticket_id,p_device_id,p_consent_id,auth.uid(),p_scope,btrim(p_audience),encode(digest(v_token,'sha256'),'hex'),now()+interval '10 minutes',p_idempotency_key)returning id into v_existing;return query select v_existing,v_token;end$$;
create or replace function public.erp_revoke_remote_access(p_tenant_id uuid,p_grant_id uuid,p_reason text,p_idempotency_key text)returns uuid language plpgsql security definer set search_path='' as $$declare v_id uuid;begin if erp_security.current_aal()<>'aal2'or not(erp_security.has_permission(p_tenant_id,'remote.revoke')or public.is_platform_staff())then raise exception 'permission and aal2 required';end if;if length(btrim(p_reason))not between 1 and 1000 or length(btrim(p_idempotency_key))not between 8 and 200 then raise exception 'invalid reason or idempotency key';end if;perform pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':'||p_grant_id::text,0));update public.erp_remote_access_grants set status='revoked',revoked_at=coalesce(revoked_at,now())where tenant_id=p_tenant_id and id=p_grant_id and status in('issued','consumed')returning id into v_id;if v_id is null and not exists(select 1 from public.erp_remote_access_grants where tenant_id=p_tenant_id and id=p_grant_id and status='revoked')then raise exception 'grant not found';end if;v_id:=p_grant_id;update public.erp_remote_sessions set status='revoked',ended_at=coalesce(ended_at,now())where tenant_id=p_tenant_id and grant_id=p_grant_id and status not in('ended','denied','failed','revoked','expired');insert into public.erp_support_ticket_events(tenant_id,ticket_id,event_type,reason,idempotency_key,created_by)select p_tenant_id,g.ticket_id,'remote_revoked',btrim(p_reason),p_idempotency_key,auth.uid()from public.erp_remote_access_grants g where g.tenant_id=p_tenant_id and g.id=p_grant_id on conflict(tenant_id,idempotency_key)do nothing;return v_id;end$$;
create or replace function public.erp_decide_remote_consent(p_tenant_id uuid,p_consent_id uuid,p_decision text,p_expires_at timestamptz,p_idempotency_key text)returns uuid language plpgsql security definer set search_path='' as $$declare v_ticket_id uuid;begin if not(erp_security.has_permission(p_tenant_id,'remote.request')or public.is_platform_staff())then raise exception 'permission denied';end if;if p_decision not in('granted','denied')or length(btrim(p_idempotency_key))not between 8 and 200 then raise exception 'invalid decision or idempotency key';end if;if p_decision='granted'and(p_expires_at is null or p_expires_at<=now()or p_expires_at>now()+interval '24 hours')then raise exception 'invalid consent expiration';end if;perform pg_advisory_xact_lock(hashtextextended(p_tenant_id::text||':'||p_consent_id::text,0));select ticket_id into v_ticket_id from public.erp_remote_consents where tenant_id=p_tenant_id and id=p_consent_id and status='pending'for update;if v_ticket_id is null then if exists(select 1 from public.erp_support_ticket_events where tenant_id=p_tenant_id and idempotency_key=p_idempotency_key)then return p_consent_id;end if;raise exception 'pending consent not found';end if;update public.erp_remote_consents set status=p_decision,valid_from=case when p_decision='granted'then now()end,expires_at=case when p_decision='granted'then p_expires_at end,decided_at=now()where tenant_id=p_tenant_id and id=p_consent_id;insert into public.erp_support_ticket_events(tenant_id,ticket_id,event_type,to_status,detail,idempotency_key,created_by)values(p_tenant_id,v_ticket_id,'remote_consent_decided',p_decision,jsonb_build_object('consent_id',p_consent_id,'expires_at',p_expires_at),p_idempotency_key,auth.uid());return p_consent_id;end$$;

do $$declare t text;begin foreach t in array array['erp_support_queues','erp_support_queue_members','erp_sla_policies','erp_sla_targets','erp_support_tickets','erp_support_ticket_events','erp_support_messages','erp_support_attachments','erp_ticket_assignments','erp_ticket_sla_clocks','erp_managed_devices','erp_device_identifiers','erp_remote_consents','erp_remote_access_grants','erp_remote_sessions','erp_remote_session_events','erp_remote_session_artifacts']loop execute format('alter table public.%I enable row level security',t);execute format('create policy %I on public.%I for select to authenticated using ((select erp_security.has_permission(tenant_id,''support.read''))or(select erp_security.has_permission(tenant_id,''support.manage''))or(select erp_security.has_permission(tenant_id,''remote.audit''))or(select public.is_platform_staff()))',t||'_select',t);execute format('revoke all on table public.%I from anon,authenticated',t);execute format('grant select on table public.%I to authenticated',t);execute format('grant all on table public.%I to service_role',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['erp_support_queues','erp_support_queue_members','erp_sla_policies','erp_sla_targets','erp_support_tickets','erp_support_messages','erp_support_attachments','erp_ticket_assignments','erp_ticket_sla_clocks','erp_managed_devices','erp_device_identifiers','erp_remote_consents']loop execute format('create policy %I on public.%I for insert to authenticated with check ((select erp_security.has_permission(tenant_id,''support.manage''))or(select erp_security.has_permission(tenant_id,''support.create''))or(select erp_security.has_permission(tenant_id,''remote.request''))or(select public.is_platform_staff()))',t||'_insert',t);execute format('grant insert on table public.%I to authenticated',t);end loop;end$$;
do $$declare t text;begin foreach t in array array['erp_support_queues','erp_sla_policies','erp_support_tickets','erp_ticket_sla_clocks','erp_managed_devices','erp_remote_consents']loop execute format('create policy %I on public.%I for update to authenticated using ((select erp_security.has_permission(tenant_id,''support.manage''))or(select erp_security.has_permission(tenant_id,''remote.request''))or(select public.is_platform_staff())) with check ((select erp_security.has_permission(tenant_id,''support.manage''))or(select erp_security.has_permission(tenant_id,''remote.request''))or(select public.is_platform_staff()))',t||'_update',t);execute format('grant update on table public.%I to authenticated',t);end loop;end$$;

-- Segurança por domínio: remove as políticas genéricas e aplica privilégio mínimo.
do $$declare t text;begin foreach t in array array['erp_support_queues','erp_support_queue_members','erp_sla_policies','erp_sla_targets','erp_support_tickets','erp_support_messages','erp_support_attachments','erp_ticket_assignments','erp_ticket_sla_clocks','erp_managed_devices','erp_device_identifiers','erp_remote_consents']loop execute format('drop policy if exists %I on public.%I',t||'_insert',t);execute format('revoke insert on table public.%I from authenticated',t);end loop;foreach t in array array['erp_support_queues','erp_sla_policies','erp_support_tickets','erp_ticket_sla_clocks','erp_managed_devices','erp_remote_consents']loop execute format('drop policy if exists %I on public.%I',t||'_update',t);execute format('revoke update on table public.%I from authenticated',t);end loop;end$$;
create policy erp_support_queues_insert on public.erp_support_queues for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_support_queue_members_insert on public.erp_support_queue_members for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.assign')or public.is_platform_staff());
create policy erp_sla_policies_insert on public.erp_sla_policies for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff());
create policy erp_sla_targets_insert on public.erp_sla_targets for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff());
create policy erp_support_messages_insert on public.erp_support_messages for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_support_attachments_insert on public.erp_support_attachments for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_ticket_assignments_insert on public.erp_ticket_assignments for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.assign')or public.is_platform_staff());
create policy erp_ticket_sla_clocks_insert on public.erp_ticket_sla_clocks for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff());
create policy erp_managed_devices_insert on public.erp_managed_devices for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_device_identifiers_insert on public.erp_device_identifiers for insert to authenticated with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_remote_consents_insert on public.erp_remote_consents for insert to authenticated with check(status='pending'and valid_from is null and expires_at is null and decided_at is null and(erp_security.has_permission(tenant_id,'remote.request')or public.is_platform_staff()));
grant insert on public.erp_support_queues,public.erp_support_queue_members,public.erp_sla_policies,public.erp_sla_targets,public.erp_support_messages,public.erp_support_attachments,public.erp_ticket_assignments,public.erp_ticket_sla_clocks,public.erp_managed_devices,public.erp_device_identifiers,public.erp_remote_consents to authenticated;
create policy erp_support_queues_update on public.erp_support_queues for update to authenticated using(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff())with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_sla_policies_update on public.erp_sla_policies for update to authenticated using(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff())with check(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff());
create policy erp_support_tickets_update on public.erp_support_tickets for update to authenticated using(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff())with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
create policy erp_ticket_sla_clocks_update on public.erp_ticket_sla_clocks for update to authenticated using(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff())with check(erp_security.has_permission(tenant_id,'support.sla')or public.is_platform_staff());
create policy erp_managed_devices_update on public.erp_managed_devices for update to authenticated using(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff())with check(erp_security.has_permission(tenant_id,'support.manage')or public.is_platform_staff());
grant update on public.erp_support_queues,public.erp_sla_policies,public.erp_support_tickets,public.erp_ticket_sla_clocks,public.erp_managed_devices to authenticated;

-- Metadados remotos exigem permissões remotas, não apenas leitura de suporte.
do $$declare t text;begin foreach t in array array['erp_remote_consents','erp_remote_access_grants','erp_remote_sessions','erp_remote_session_events','erp_remote_session_artifacts']loop execute format('drop policy if exists %I on public.%I',t||'_select',t);end loop;end$$;
create policy erp_remote_consents_select on public.erp_remote_consents for select to authenticated using(erp_security.has_permission(tenant_id,'remote.request')or erp_security.has_permission(tenant_id,'remote.audit')or public.is_platform_staff());
create policy erp_remote_access_grants_select on public.erp_remote_access_grants for select to authenticated using(erp_security.has_permission(tenant_id,'remote.audit')or public.is_platform_staff());
create policy erp_remote_sessions_select on public.erp_remote_sessions for select to authenticated using(erp_security.has_permission(tenant_id,'remote.connect')or erp_security.has_permission(tenant_id,'remote.audit')or public.is_platform_staff());
create policy erp_remote_session_events_select on public.erp_remote_session_events for select to authenticated using(erp_security.has_permission(tenant_id,'remote.audit')or public.is_platform_staff());
create policy erp_remote_session_artifacts_select on public.erp_remote_session_artifacts for select to authenticated using(erp_security.has_permission(tenant_id,'remote.audit')or public.is_platform_staff());

-- Coerência composta entre ticket, mensagem, dispositivo e consentimento.
alter table public.erp_support_messages add constraint erp_support_messages_tenant_ticket_id_key unique(tenant_id,ticket_id,id);
alter table public.erp_support_attachments drop constraint erp_support_attachments_tenant_id_message_id_fkey,add constraint erp_support_attachments_message_ticket_fkey foreign key(tenant_id,ticket_id,message_id)references public.erp_support_messages(tenant_id,ticket_id,id)on delete cascade;
alter table public.erp_remote_consents add constraint erp_remote_consents_tenant_ticket_device_id_key unique(tenant_id,ticket_id,device_id,id);
alter table public.erp_remote_access_grants drop constraint erp_remote_access_grants_tenant_id_consent_id_fkey,add constraint erp_remote_access_grants_consent_context_fkey foreign key(tenant_id,ticket_id,device_id,consent_id)references public.erp_remote_consents(tenant_id,ticket_id,device_id,id)on delete restrict;
revoke execute on function public.erp_create_support_ticket(uuid,uuid,uuid,text,text,text,text,text,text),public.erp_issue_remote_access_grant(uuid,uuid,uuid,uuid,text[],text,text),public.erp_revoke_remote_access(uuid,uuid,text,text),public.erp_decide_remote_consent(uuid,uuid,text,timestamptz,text)from public,anon;
grant execute on function public.erp_create_support_ticket(uuid,uuid,uuid,text,text,text,text,text,text),public.erp_issue_remote_access_grant(uuid,uuid,uuid,uuid,text[],text,text),public.erp_revoke_remote_access(uuid,uuid,text,text),public.erp_decide_remote_consent(uuid,uuid,text,timestamptz,text)to authenticated,service_role;
commit;
