-- ConnectionCyber - M16: extensao contratual das capacidades canonicas da 0016.
begin;

alter table public.erp_capability_catalog add column risk_level text not null default 'standard';
alter table public.erp_capability_catalog add constraint erp_capability_catalog_risk_check check(risk_level in('standard','controlled','critical'));
insert into public.erp_capability_catalog(key,name,description,category,risk_level)values('device.agent','Agente local','Integracao protegida com perifericos.','device','critical')on conflict(key)do update set name=excluded.name,description=excluded.description,category=excluded.category,risk_level=excluded.risk_level,active=true;
update public.erp_capability_catalog set risk_level=case when key in('support.remote','fiscal','migration','device.agent')then'critical'when key in('sales.pos','finance','food.table_service')then'controlled'else'standard'end;

alter table public.erp_tenant_capabilities add column source text not null default'migration',add column contract_version integer not null default 1,add column evidence_hash text;
update public.erp_tenant_capabilities set evidence_hash=md5(tenant_id::text||':'||capability_key)||md5(capability_key||':'||tenant_id::text)where evidence_hash is null;
alter table public.erp_tenant_capabilities alter column evidence_hash set not null,add constraint erp_tenant_capabilities_source_check check(source in('blueprint','contract','migration')),add constraint erp_tenant_capabilities_contract_version_check check(contract_version>0),add constraint erp_tenant_capabilities_evidence_hash_check check(evidence_hash~'^[a-f0-9]{64}$');

create table public.erp_tenant_capability_exceptions(id uuid primary key default gen_random_uuid(),tenant_id uuid not null references public.tenants(id)on delete cascade,capability_key text not null references public.erp_capability_catalog(key)on delete restrict,effect text not null check(effect in('allow','deny')),reason_hash text not null check(reason_hash~'^[a-f0-9]{64}$'),approval_ref text not null check(approval_ref~'^approval:sha256:[a-f0-9]{64}$'),effective_from timestamptz not null,expires_at timestamptz not null,status text not null default'active'check(status in('active','revoked','expired')),created_at timestamptz not null default now(),revoked_at timestamptz,unique(tenant_id,id),unique(tenant_id,capability_key,approval_ref),check(expires_at>effective_from),check((status='revoked'and revoked_at is not null)or(status<>'revoked'and revoked_at is null)));
create index idx_capability_exceptions_tenant_active on public.erp_tenant_capability_exceptions(tenant_id,capability_key,status,effective_from,expires_at);
insert into public.erp_permissions(key,name,description,category)values('capabilities.read','Consultar capacidades','Consulta capacidades efetivas do tenant.','foundation')on conflict(key)do update set name=excluded.name,description=excluded.description,category=excluded.category,active=true;

alter table public.erp_tenant_capability_exceptions enable row level security;
revoke all on public.erp_tenant_capability_exceptions from anon,authenticated,service_role;
grant select on public.erp_tenant_capability_exceptions to authenticated,service_role;
grant insert on public.erp_tenant_capability_exceptions to service_role;
create policy erp_tenant_capability_exceptions_select on public.erp_tenant_capability_exceptions for select to authenticated using(erp_security.has_permission(tenant_id,'capabilities.read')or erp_security.has_permission(tenant_id,'capabilities.manage')or erp_security.is_tenant_member(tenant_id)or public.is_platform_staff());
revoke insert,update,delete on public.erp_capability_catalog,public.erp_tenant_capabilities from service_role;

create or replace function public.erp_set_tenant_capability(p_tenant_id uuid,p_capability_key text,p_status text,p_source text,p_contract_version integer,p_evidence_hash text,p_starts_at timestamptz default now(),p_ends_at timestamptz default null)returns uuid language plpgsql security definer set search_path=''as $$declare v_id uuid;begin if auth.role()<>'service_role'then raise exception 'broker only';end if;if p_status not in('trial','active','suspended','disabled')or p_source not in('blueprint','contract','migration')or p_contract_version<1 or p_evidence_hash!~'^[a-f0-9]{64}$'or(p_ends_at is not null and(p_starts_at is null or p_ends_at<=p_starts_at))then raise exception 'invalid entitlement';end if;insert into public.erp_tenant_capabilities(tenant_id,capability_key,status,source,contract_version,evidence_hash,starts_at,ends_at)values(p_tenant_id,p_capability_key,p_status,p_source,p_contract_version,p_evidence_hash,p_starts_at,p_ends_at)on conflict(tenant_id,capability_key)do update set status=excluded.status,source=excluded.source,contract_version=excluded.contract_version,evidence_hash=excluded.evidence_hash,starts_at=excluded.starts_at,ends_at=excluded.ends_at,updated_at=now()returning id into v_id;return v_id;end$$;

create or replace function public.erp_resolve_tenant_capabilities(p_tenant_id uuid,p_at timestamptz default now())returns table(capability_key text,status text,source text)language plpgsql stable security invoker set search_path=''as $$begin if not(auth.role()='service_role'or erp_security.has_permission(p_tenant_id,'capabilities.read')or erp_security.has_permission(p_tenant_id,'capabilities.manage')or erp_security.is_tenant_member(p_tenant_id)or public.is_platform_staff())then raise exception 'capability access denied';end if;return query with entitlement as(select e.capability_key,e.status,e.source from public.erp_tenant_capabilities e where e.tenant_id=p_tenant_id and(e.starts_at is null or e.starts_at<=p_at)and(e.ends_at is null or e.ends_at>p_at)),exception_state as(select x.capability_key,bool_or(x.effect='deny')denied,bool_or(x.effect='allow')allowed from public.erp_tenant_capability_exceptions x where x.tenant_id=p_tenant_id and x.status='active'and x.effective_from<=p_at and x.expires_at>p_at group by x.capability_key)select c.key,case when coalesce(x.denied,false)then'disabled'when coalesce(x.allowed,false)then'active'when e.status in('trial','active')then e.status else'disabled'end,case when coalesce(x.denied,false)then'exception_deny'when coalesce(x.allowed,false)then'exception_allow'when e.capability_key is not null then e.source else'default_deny'end from public.erp_capability_catalog c left join entitlement e on e.capability_key=c.key left join exception_state x on x.capability_key=c.key where c.active order by c.key;end$$;

create or replace function public.erp_revoke_capability_exception(p_tenant_id uuid,p_exception_id uuid,p_revoked_at timestamptz default now())returns boolean language plpgsql security definer set search_path=''as $$declare v_status text;begin if auth.role()<>'service_role'then raise exception 'broker only';end if;if p_tenant_id is null or p_exception_id is null or p_revoked_at is null or p_revoked_at>now()+interval'5 minutes'then raise exception 'invalid revocation';end if;select status into v_status from public.erp_tenant_capability_exceptions where tenant_id=p_tenant_id and id=p_exception_id for update;if v_status is null then raise exception 'exception not found';end if;if v_status='revoked'then return false;end if;if v_status<>'active'then raise exception 'only active exception can be revoked';end if;update public.erp_tenant_capability_exceptions set status='revoked',revoked_at=p_revoked_at where tenant_id=p_tenant_id and id=p_exception_id;return true;end$$;

revoke execute on function public.erp_set_tenant_capability(uuid,text,text,text,integer,text,timestamptz,timestamptz),public.erp_resolve_tenant_capabilities(uuid,timestamptz),public.erp_revoke_capability_exception(uuid,uuid,timestamptz)from public,anon,authenticated,service_role;
grant execute on function public.erp_resolve_tenant_capabilities(uuid,timestamptz)to authenticated,service_role;
grant execute on function public.erp_set_tenant_capability(uuid,text,text,text,integer,text,timestamptz,timestamptz),public.erp_revoke_capability_exception(uuid,uuid,timestamptz)to service_role;
commit;
